/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class atm2veg_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected atm2veg_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(atm2veg_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_atm2veg_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIngppall(double value) {
    temcoreJNI.atm2veg_bgc_ingppall_set(swigCPtr, this, value);
  }

  public double getIngppall() {
    return temcoreJNI.atm2veg_bgc_ingppall_get(swigCPtr, this);
  }

  public void setIngpp(double[] value) {
    temcoreJNI.atm2veg_bgc_ingpp_set(swigCPtr, this, value);
  }

  public double[] getIngpp() {
    return temcoreJNI.atm2veg_bgc_ingpp_get(swigCPtr, this);
  }

  public void setGppall(double value) {
    temcoreJNI.atm2veg_bgc_gppall_set(swigCPtr, this, value);
  }

  public double getGppall() {
    return temcoreJNI.atm2veg_bgc_gppall_get(swigCPtr, this);
  }

  public void setGpp(double[] value) {
    temcoreJNI.atm2veg_bgc_gpp_set(swigCPtr, this, value);
  }

  public double[] getGpp() {
    return temcoreJNI.atm2veg_bgc_gpp_get(swigCPtr, this);
  }

  public void setInnppall(double value) {
    temcoreJNI.atm2veg_bgc_innppall_set(swigCPtr, this, value);
  }

  public double getInnppall() {
    return temcoreJNI.atm2veg_bgc_innppall_get(swigCPtr, this);
  }

  public void setInnpp(double[] value) {
    temcoreJNI.atm2veg_bgc_innpp_set(swigCPtr, this, value);
  }

  public double[] getInnpp() {
    return temcoreJNI.atm2veg_bgc_innpp_get(swigCPtr, this);
  }

  public void setNppall(double value) {
    temcoreJNI.atm2veg_bgc_nppall_set(swigCPtr, this, value);
  }

  public double getNppall() {
    return temcoreJNI.atm2veg_bgc_nppall_get(swigCPtr, this);
  }

  public void setNpp(double[] value) {
    temcoreJNI.atm2veg_bgc_npp_set(swigCPtr, this, value);
  }

  public double[] getNpp() {
    return temcoreJNI.atm2veg_bgc_npp_get(swigCPtr, this);
  }

  public atm2veg_bgc() {
    this(temcoreJNI.new_atm2veg_bgc(), true);
  }

}
