/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class atm2lnd_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected atm2lnd_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(atm2lnd_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_atm2lnd_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNdep(double value) {
    temcoreJNI.atm2lnd_bgc_ndep_set(swigCPtr, this, value);
  }

  public double getNdep() {
    return temcoreJNI.atm2lnd_bgc_ndep_get(swigCPtr, this);
  }

  public void setOzon(double value) {
    temcoreJNI.atm2lnd_bgc_ozon_set(swigCPtr, this, value);
  }

  public double getOzon() {
    return temcoreJNI.atm2lnd_bgc_ozon_get(swigCPtr, this);
  }

  public atm2lnd_bgc() {
    this(temcoreJNI.new_atm2lnd_bgc(), true);
  }

}
