/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class CohortData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CohortData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CohortData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_CohortData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CohortData() {
    this(temcoreJNI.new_CohortData(), true);
  }

  public void clear() {
    temcoreJNI.CohortData_clear(swigCPtr, this);
  }

  public void setChtid(int value) {
    temcoreJNI.CohortData_chtid_set(swigCPtr, this, value);
  }

  public int getChtid() {
    return temcoreJNI.CohortData_chtid_get(swigCPtr, this);
  }

  public void setYear(int value) {
    temcoreJNI.CohortData_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return temcoreJNI.CohortData_year_get(swigCPtr, this);
  }

  public void setMonth(int value) {
    temcoreJNI.CohortData_month_set(swigCPtr, this, value);
  }

  public int getMonth() {
    return temcoreJNI.CohortData_month_get(swigCPtr, this);
  }

  public void setDay(int value) {
    temcoreJNI.CohortData_day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return temcoreJNI.CohortData_day_get(swigCPtr, this);
  }

  public void setCmttype(int value) {
    temcoreJNI.CohortData_cmttype_set(swigCPtr, this, value);
  }

  public int getCmttype() {
    return temcoreJNI.CohortData_cmttype_get(swigCPtr, this);
  }

  public void setYrsdist(int value) {
    temcoreJNI.CohortData_yrsdist_set(swigCPtr, this, value);
  }

  public int getYrsdist() {
    return temcoreJNI.CohortData_yrsdist_get(swigCPtr, this);
  }

  public void setHasnonvascular(boolean value) {
    temcoreJNI.CohortData_hasnonvascular_set(swigCPtr, this, value);
  }

  public boolean getHasnonvascular() {
    return temcoreJNI.CohortData_hasnonvascular_get(swigCPtr, this);
  }

  public void setAct_vegset(int value) {
    temcoreJNI.CohortData_act_vegset_set(swigCPtr, this, value);
  }

  public int getAct_vegset() {
    return temcoreJNI.CohortData_act_vegset_get(swigCPtr, this);
  }

  public void setVegyear(int[] value) {
    temcoreJNI.CohortData_vegyear_set(swigCPtr, this, value);
  }

  public int[] getVegyear() {
    return temcoreJNI.CohortData_vegyear_get(swigCPtr, this);
  }

  public void setVegtype(int[] value) {
    temcoreJNI.CohortData_vegtype_set(swigCPtr, this, value);
  }

  public int[] getVegtype() {
    return temcoreJNI.CohortData_vegtype_get(swigCPtr, this);
  }

  public void setVegfrac(double[] value) {
    temcoreJNI.CohortData_vegfrac_set(swigCPtr, this, value);
  }

  public double[] getVegfrac() {
    return temcoreJNI.CohortData_vegfrac_get(swigCPtr, this);
  }

  public void setAct_fireset(int value) {
    temcoreJNI.CohortData_act_fireset_set(swigCPtr, this, value);
  }

  public int getAct_fireset() {
    return temcoreJNI.CohortData_act_fireset_get(swigCPtr, this);
  }

  public void setFireyear(int[] value) {
    temcoreJNI.CohortData_fireyear_set(swigCPtr, this, value);
  }

  public int[] getFireyear() {
    return temcoreJNI.CohortData_fireyear_get(swigCPtr, this);
  }

  public void setFireseason(int[] value) {
    temcoreJNI.CohortData_fireseason_set(swigCPtr, this, value);
  }

  public int[] getFireseason() {
    return temcoreJNI.CohortData_fireseason_get(swigCPtr, this);
  }

  public void setFiresize(int[] value) {
    temcoreJNI.CohortData_firesize_set(swigCPtr, this, value);
  }

  public int[] getFiresize() {
    return temcoreJNI.CohortData_firesize_get(swigCPtr, this);
  }

  public void setFireseverity(int[] value) {
    temcoreJNI.CohortData_fireseverity_set(swigCPtr, this, value);
  }

  public int[] getFireseverity() {
    return temcoreJNI.CohortData_fireseverity_get(swigCPtr, this);
  }

  public void setAct_atm_drv_yr(int value) {
    temcoreJNI.CohortData_act_atm_drv_yr_set(swigCPtr, this, value);
  }

  public int getAct_atm_drv_yr() {
    return temcoreJNI.CohortData_act_atm_drv_yr_get(swigCPtr, this);
  }

  public void setTair(float[] value) {
    temcoreJNI.CohortData_tair_set(swigCPtr, this, value);
  }

  public float[] getTair() {
    return temcoreJNI.CohortData_tair_get(swigCPtr, this);
  }

  public void setPrec(float[] value) {
    temcoreJNI.CohortData_prec_set(swigCPtr, this, value);
  }

  public float[] getPrec() {
    return temcoreJNI.CohortData_prec_get(swigCPtr, this);
  }

  public void setNirr(float[] value) {
    temcoreJNI.CohortData_nirr_set(swigCPtr, this, value);
  }

  public float[] getNirr() {
    return temcoreJNI.CohortData_nirr_get(swigCPtr, this);
  }

  public void setVapo(float[] value) {
    temcoreJNI.CohortData_vapo_set(swigCPtr, this, value);
  }

  public float[] getVapo() {
    return temcoreJNI.CohortData_vapo_get(swigCPtr, this);
  }

  public void setAct_ndep_yr(int value) {
    temcoreJNI.CohortData_act_ndep_yr_set(swigCPtr, this, value);
  }

  public int getAct_ndep_yr() {
    return temcoreJNI.CohortData_act_ndep_yr_get(swigCPtr, this);
  }

  public void setNdep(float[] value) {
    temcoreJNI.CohortData_ndep_set(swigCPtr, this, value);
  }

  public float[] getNdep() {
    return temcoreJNI.CohortData_ndep_get(swigCPtr, this);
  }

  public void setAct_ozon_yr(int value) {
    temcoreJNI.CohortData_act_ozon_yr_set(swigCPtr, this, value);
  }

  public int getAct_ozon_yr() {
    return temcoreJNI.CohortData_act_ozon_yr_get(swigCPtr, this);
  }

  public void setOzon(float[] value) {
    temcoreJNI.CohortData_ozon_set(swigCPtr, this, value);
  }

  public float[] getOzon() {
    return temcoreJNI.CohortData_ozon_get(swigCPtr, this);
  }

  public void setD_tair(float[] value) {
    temcoreJNI.CohortData_d_tair_set(swigCPtr, this, value);
  }

  public float[] getD_tair() {
    return temcoreJNI.CohortData_d_tair_get(swigCPtr, this);
  }

  public void setD_prec(float[] value) {
    temcoreJNI.CohortData_d_prec_set(swigCPtr, this, value);
  }

  public float[] getD_prec() {
    return temcoreJNI.CohortData_d_prec_get(swigCPtr, this);
  }

  public void setD_nirr(float[] value) {
    temcoreJNI.CohortData_d_nirr_set(swigCPtr, this, value);
  }

  public float[] getD_nirr() {
    return temcoreJNI.CohortData_d_nirr_get(swigCPtr, this);
  }

  public void setD_vapo(float[] value) {
    temcoreJNI.CohortData_d_vapo_set(swigCPtr, this, value);
  }

  public float[] getD_vapo() {
    return temcoreJNI.CohortData_d_vapo_get(swigCPtr, this);
  }

  public void setD_veg(vegstate_dim value) {
    temcoreJNI.CohortData_d_veg_set(swigCPtr, this, vegstate_dim.getCPtr(value), value);
  }

  public vegstate_dim getD_veg() {
    long cPtr = temcoreJNI.CohortData_d_veg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_dim(cPtr, false);
  }

  public void setM_veg(vegstate_dim value) {
    temcoreJNI.CohortData_m_veg_set(swigCPtr, this, vegstate_dim.getCPtr(value), value);
  }

  public vegstate_dim getM_veg() {
    long cPtr = temcoreJNI.CohortData_m_veg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_dim(cPtr, false);
  }

  public void setY_veg(vegstate_dim value) {
    temcoreJNI.CohortData_y_veg_set(swigCPtr, this, vegstate_dim.getCPtr(value), value);
  }

  public vegstate_dim getY_veg() {
    long cPtr = temcoreJNI.CohortData_y_veg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_dim(cPtr, false);
  }

  public void setD_vegd(vegdiag_dim value) {
    temcoreJNI.CohortData_d_vegd_set(swigCPtr, this, vegdiag_dim.getCPtr(value), value);
  }

  public vegdiag_dim getD_vegd() {
    long cPtr = temcoreJNI.CohortData_d_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_dim(cPtr, false);
  }

  public void setM_vegd(vegdiag_dim value) {
    temcoreJNI.CohortData_m_vegd_set(swigCPtr, this, vegdiag_dim.getCPtr(value), value);
  }

  public vegdiag_dim getM_vegd() {
    long cPtr = temcoreJNI.CohortData_m_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_dim(cPtr, false);
  }

  public void setY_vegd(vegdiag_dim value) {
    temcoreJNI.CohortData_y_vegd_set(swigCPtr, this, vegdiag_dim.getCPtr(value), value);
  }

  public vegdiag_dim getY_vegd() {
    long cPtr = temcoreJNI.CohortData_y_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_dim(cPtr, false);
  }

  public void setD_snow(snwstate_dim value) {
    temcoreJNI.CohortData_d_snow_set(swigCPtr, this, snwstate_dim.getCPtr(value), value);
  }

  public snwstate_dim getD_snow() {
    long cPtr = temcoreJNI.CohortData_d_snow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_dim(cPtr, false);
  }

  public void setM_snow(snwstate_dim value) {
    temcoreJNI.CohortData_m_snow_set(swigCPtr, this, snwstate_dim.getCPtr(value), value);
  }

  public snwstate_dim getM_snow() {
    long cPtr = temcoreJNI.CohortData_m_snow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_dim(cPtr, false);
  }

  public void setY_snow(snwstate_dim value) {
    temcoreJNI.CohortData_y_snow_set(swigCPtr, this, snwstate_dim.getCPtr(value), value);
  }

  public snwstate_dim getY_snow() {
    long cPtr = temcoreJNI.CohortData_y_snow_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_dim(cPtr, false);
  }

  public void setD_soil(soistate_dim value) {
    temcoreJNI.CohortData_d_soil_set(swigCPtr, this, soistate_dim.getCPtr(value), value);
  }

  public soistate_dim getD_soil() {
    long cPtr = temcoreJNI.CohortData_d_soil_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_dim(cPtr, false);
  }

  public void setM_soil(soistate_dim value) {
    temcoreJNI.CohortData_m_soil_set(swigCPtr, this, soistate_dim.getCPtr(value), value);
  }

  public soistate_dim getM_soil() {
    long cPtr = temcoreJNI.CohortData_m_soil_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_dim(cPtr, false);
  }

  public void setY_soil(soistate_dim value) {
    temcoreJNI.CohortData_y_soil_set(swigCPtr, this, soistate_dim.getCPtr(value), value);
  }

  public soistate_dim getY_soil() {
    long cPtr = temcoreJNI.CohortData_y_soil_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_dim(cPtr, false);
  }

  public void setPrveetmxque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.CohortData_prveetmxque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getPrveetmxque() {
    long cPtr = temcoreJNI.CohortData_prveetmxque_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_dequeT_double_t(cPtr, false);
  }

  public void setPrvunnormleafmxque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.CohortData_prvunnormleafmxque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getPrvunnormleafmxque() {
    long cPtr = temcoreJNI.CohortData_prvunnormleafmxque_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_dequeT_double_t(cPtr, false);
  }

  public void setPrvgrowingttimeque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.CohortData_prvgrowingttimeque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getPrvgrowingttimeque() {
    long cPtr = temcoreJNI.CohortData_prvgrowingttimeque_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_dequeT_double_t(cPtr, false);
  }

  public void setToptque(SWIGTYPE_p_dequeT_double_t value) {
    temcoreJNI.CohortData_toptque_set(swigCPtr, this, SWIGTYPE_p_dequeT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_dequeT_double_t getToptque() {
    long cPtr = temcoreJNI.CohortData_toptque_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_dequeT_double_t(cPtr, false);
  }

  public void setRd(RegionData value) {
    temcoreJNI.CohortData_rd_set(swigCPtr, this, RegionData.getCPtr(value), value);
  }

  public RegionData getRd() {
    long cPtr = temcoreJNI.CohortData_rd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RegionData(cPtr, false);
  }

  public void setGd(GridData value) {
    temcoreJNI.CohortData_gd_set(swigCPtr, this, GridData.getCPtr(value), value);
  }

  public GridData getGd() {
    long cPtr = temcoreJNI.CohortData_gd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GridData(cPtr, false);
  }

  public void beginOfYear() {
    temcoreJNI.CohortData_beginOfYear(swigCPtr, this);
  }

  public void beginOfMonth() {
    temcoreJNI.CohortData_beginOfMonth(swigCPtr, this);
  }

  public void endOfDay(int dinm) {
    temcoreJNI.CohortData_endOfDay(swigCPtr, this, dinm);
  }

  public void endOfDay_snow(int dinm) {
    temcoreJNI.CohortData_endOfDay_snow(swigCPtr, this, dinm);
  }

  public void endOfMonth() {
    temcoreJNI.CohortData_endOfMonth(swigCPtr, this);
  }

  public void endOfYear() {
    temcoreJNI.CohortData_endOfYear(swigCPtr, this);
  }

}
