/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class Controller {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Controller(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Controller obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_Controller(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Controller() {
    this(temcoreJNI.new_Controller(), true);
  }

  public void setControlfile(String value) {
    temcoreJNI.Controller_controlfile_set(swigCPtr, this, value);
  }

  public String getControlfile() {
    return temcoreJNI.Controller_controlfile_get(swigCPtr, this);
  }

  public void ctrl4run(ModelData md) {
    temcoreJNI.Controller_ctrl4run(swigCPtr, this, ModelData.getCPtr(md), md);
  }

  public void assignJcontrolfile(String jcontrolfile) {
    temcoreJNI.Controller_assignJcontrolfile(swigCPtr, this, jcontrolfile);
  }

}
