/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class EnvData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EnvData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EnvData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_EnvData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EnvData() {
    this(temcoreJNI.new_EnvData(), true);
  }

  public void clear() {
    temcoreJNI.EnvData_clear(swigCPtr, this);
  }

  public void setD_atms(atmstate_env value) {
    temcoreJNI.EnvData_d_atms_set(swigCPtr, this, atmstate_env.getCPtr(value), value);
  }

  public atmstate_env getD_atms() {
    long cPtr = temcoreJNI.EnvData_d_atms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmstate_env(cPtr, false);
  }

  public void setD_vegs(vegstate_env value) {
    temcoreJNI.EnvData_d_vegs_set(swigCPtr, this, vegstate_env.getCPtr(value), value);
  }

  public vegstate_env getD_vegs() {
    long cPtr = temcoreJNI.EnvData_d_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_env(cPtr, false);
  }

  public void setD_snws(snwstate_env value) {
    temcoreJNI.EnvData_d_snws_set(swigCPtr, this, snwstate_env.getCPtr(value), value);
  }

  public snwstate_env getD_snws() {
    long cPtr = temcoreJNI.EnvData_d_snws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_env(cPtr, false);
  }

  public void setD_sois(soistate_env value) {
    temcoreJNI.EnvData_d_sois_set(swigCPtr, this, soistate_env.getCPtr(value), value);
  }

  public soistate_env getD_sois() {
    long cPtr = temcoreJNI.EnvData_d_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_env(cPtr, false);
  }

  public void setD_atmd(atmdiag_env value) {
    temcoreJNI.EnvData_d_atmd_set(swigCPtr, this, atmdiag_env.getCPtr(value), value);
  }

  public atmdiag_env getD_atmd() {
    long cPtr = temcoreJNI.EnvData_d_atmd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmdiag_env(cPtr, false);
  }

  public void setD_vegd(vegdiag_env value) {
    temcoreJNI.EnvData_d_vegd_set(swigCPtr, this, vegdiag_env.getCPtr(value), value);
  }

  public vegdiag_env getD_vegd() {
    long cPtr = temcoreJNI.EnvData_d_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_env(cPtr, false);
  }

  public void setD_snwd(snwdiag_env value) {
    temcoreJNI.EnvData_d_snwd_set(swigCPtr, this, snwdiag_env.getCPtr(value), value);
  }

  public snwdiag_env getD_snwd() {
    long cPtr = temcoreJNI.EnvData_d_snwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwdiag_env(cPtr, false);
  }

  public void setD_soid(soidiag_env value) {
    temcoreJNI.EnvData_d_soid_set(swigCPtr, this, soidiag_env.getCPtr(value), value);
  }

  public soidiag_env getD_soid() {
    long cPtr = temcoreJNI.EnvData_d_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_env(cPtr, false);
  }

  public void setD_l2a(lnd2atm_env value) {
    temcoreJNI.EnvData_d_l2a_set(swigCPtr, this, lnd2atm_env.getCPtr(value), value);
  }

  public lnd2atm_env getD_l2a() {
    long cPtr = temcoreJNI.EnvData_d_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_env(cPtr, false);
  }

  public void setD_a2l(atm2lnd_env value) {
    temcoreJNI.EnvData_d_a2l_set(swigCPtr, this, atm2lnd_env.getCPtr(value), value);
  }

  public atm2lnd_env getD_a2l() {
    long cPtr = temcoreJNI.EnvData_d_a2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2lnd_env(cPtr, false);
  }

  public void setD_a2v(atm2veg_env value) {
    temcoreJNI.EnvData_d_a2v_set(swigCPtr, this, atm2veg_env.getCPtr(value), value);
  }

  public atm2veg_env getD_a2v() {
    long cPtr = temcoreJNI.EnvData_d_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_env(cPtr, false);
  }

  public void setD_v2a(veg2atm_env value) {
    temcoreJNI.EnvData_d_v2a_set(swigCPtr, this, veg2atm_env.getCPtr(value), value);
  }

  public veg2atm_env getD_v2a() {
    long cPtr = temcoreJNI.EnvData_d_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_env(cPtr, false);
  }

  public void setD_v2g(veg2gnd_env value) {
    temcoreJNI.EnvData_d_v2g_set(swigCPtr, this, veg2gnd_env.getCPtr(value), value);
  }

  public veg2gnd_env getD_v2g() {
    long cPtr = temcoreJNI.EnvData_d_v2g_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2gnd_env(cPtr, false);
  }

  public void setD_soi2l(soi2lnd_env value) {
    temcoreJNI.EnvData_d_soi2l_set(swigCPtr, this, soi2lnd_env.getCPtr(value), value);
  }

  public soi2lnd_env getD_soi2l() {
    long cPtr = temcoreJNI.EnvData_d_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_env(cPtr, false);
  }

  public void setD_soi2a(soi2atm_env value) {
    temcoreJNI.EnvData_d_soi2a_set(swigCPtr, this, soi2atm_env.getCPtr(value), value);
  }

  public soi2atm_env getD_soi2a() {
    long cPtr = temcoreJNI.EnvData_d_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_env(cPtr, false);
  }

  public void setD_snw2a(snw2atm_env value) {
    temcoreJNI.EnvData_d_snw2a_set(swigCPtr, this, snw2atm_env.getCPtr(value), value);
  }

  public snw2atm_env getD_snw2a() {
    long cPtr = temcoreJNI.EnvData_d_snw2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2atm_env(cPtr, false);
  }

  public void setD_snw2soi(snw2soi_env value) {
    temcoreJNI.EnvData_d_snw2soi_set(swigCPtr, this, snw2soi_env.getCPtr(value), value);
  }

  public snw2soi_env getD_snw2soi() {
    long cPtr = temcoreJNI.EnvData_d_snw2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2soi_env(cPtr, false);
  }

  public void setM_atms(atmstate_env value) {
    temcoreJNI.EnvData_m_atms_set(swigCPtr, this, atmstate_env.getCPtr(value), value);
  }

  public atmstate_env getM_atms() {
    long cPtr = temcoreJNI.EnvData_m_atms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmstate_env(cPtr, false);
  }

  public void setM_vegs(vegstate_env value) {
    temcoreJNI.EnvData_m_vegs_set(swigCPtr, this, vegstate_env.getCPtr(value), value);
  }

  public vegstate_env getM_vegs() {
    long cPtr = temcoreJNI.EnvData_m_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_env(cPtr, false);
  }

  public void setM_snws(snwstate_env value) {
    temcoreJNI.EnvData_m_snws_set(swigCPtr, this, snwstate_env.getCPtr(value), value);
  }

  public snwstate_env getM_snws() {
    long cPtr = temcoreJNI.EnvData_m_snws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_env(cPtr, false);
  }

  public void setM_sois(soistate_env value) {
    temcoreJNI.EnvData_m_sois_set(swigCPtr, this, soistate_env.getCPtr(value), value);
  }

  public soistate_env getM_sois() {
    long cPtr = temcoreJNI.EnvData_m_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_env(cPtr, false);
  }

  public void setM_atmd(atmdiag_env value) {
    temcoreJNI.EnvData_m_atmd_set(swigCPtr, this, atmdiag_env.getCPtr(value), value);
  }

  public atmdiag_env getM_atmd() {
    long cPtr = temcoreJNI.EnvData_m_atmd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmdiag_env(cPtr, false);
  }

  public void setM_vegd(vegdiag_env value) {
    temcoreJNI.EnvData_m_vegd_set(swigCPtr, this, vegdiag_env.getCPtr(value), value);
  }

  public vegdiag_env getM_vegd() {
    long cPtr = temcoreJNI.EnvData_m_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_env(cPtr, false);
  }

  public void setM_snwd(snwdiag_env value) {
    temcoreJNI.EnvData_m_snwd_set(swigCPtr, this, snwdiag_env.getCPtr(value), value);
  }

  public snwdiag_env getM_snwd() {
    long cPtr = temcoreJNI.EnvData_m_snwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwdiag_env(cPtr, false);
  }

  public void setM_soid(soidiag_env value) {
    temcoreJNI.EnvData_m_soid_set(swigCPtr, this, soidiag_env.getCPtr(value), value);
  }

  public soidiag_env getM_soid() {
    long cPtr = temcoreJNI.EnvData_m_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_env(cPtr, false);
  }

  public void setM_l2a(lnd2atm_env value) {
    temcoreJNI.EnvData_m_l2a_set(swigCPtr, this, lnd2atm_env.getCPtr(value), value);
  }

  public lnd2atm_env getM_l2a() {
    long cPtr = temcoreJNI.EnvData_m_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_env(cPtr, false);
  }

  public void setM_a2l(atm2lnd_env value) {
    temcoreJNI.EnvData_m_a2l_set(swigCPtr, this, atm2lnd_env.getCPtr(value), value);
  }

  public atm2lnd_env getM_a2l() {
    long cPtr = temcoreJNI.EnvData_m_a2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2lnd_env(cPtr, false);
  }

  public void setM_a2v(atm2veg_env value) {
    temcoreJNI.EnvData_m_a2v_set(swigCPtr, this, atm2veg_env.getCPtr(value), value);
  }

  public atm2veg_env getM_a2v() {
    long cPtr = temcoreJNI.EnvData_m_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_env(cPtr, false);
  }

  public void setM_v2a(veg2atm_env value) {
    temcoreJNI.EnvData_m_v2a_set(swigCPtr, this, veg2atm_env.getCPtr(value), value);
  }

  public veg2atm_env getM_v2a() {
    long cPtr = temcoreJNI.EnvData_m_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_env(cPtr, false);
  }

  public void setM_v2g(veg2gnd_env value) {
    temcoreJNI.EnvData_m_v2g_set(swigCPtr, this, veg2gnd_env.getCPtr(value), value);
  }

  public veg2gnd_env getM_v2g() {
    long cPtr = temcoreJNI.EnvData_m_v2g_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2gnd_env(cPtr, false);
  }

  public void setM_soi2l(soi2lnd_env value) {
    temcoreJNI.EnvData_m_soi2l_set(swigCPtr, this, soi2lnd_env.getCPtr(value), value);
  }

  public soi2lnd_env getM_soi2l() {
    long cPtr = temcoreJNI.EnvData_m_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_env(cPtr, false);
  }

  public void setM_soi2a(soi2atm_env value) {
    temcoreJNI.EnvData_m_soi2a_set(swigCPtr, this, soi2atm_env.getCPtr(value), value);
  }

  public soi2atm_env getM_soi2a() {
    long cPtr = temcoreJNI.EnvData_m_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_env(cPtr, false);
  }

  public void setM_snw2a(snw2atm_env value) {
    temcoreJNI.EnvData_m_snw2a_set(swigCPtr, this, snw2atm_env.getCPtr(value), value);
  }

  public snw2atm_env getM_snw2a() {
    long cPtr = temcoreJNI.EnvData_m_snw2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2atm_env(cPtr, false);
  }

  public void setM_snw2soi(snw2soi_env value) {
    temcoreJNI.EnvData_m_snw2soi_set(swigCPtr, this, snw2soi_env.getCPtr(value), value);
  }

  public snw2soi_env getM_snw2soi() {
    long cPtr = temcoreJNI.EnvData_m_snw2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2soi_env(cPtr, false);
  }

  public void setY_atms(atmstate_env value) {
    temcoreJNI.EnvData_y_atms_set(swigCPtr, this, atmstate_env.getCPtr(value), value);
  }

  public atmstate_env getY_atms() {
    long cPtr = temcoreJNI.EnvData_y_atms_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmstate_env(cPtr, false);
  }

  public void setY_vegs(vegstate_env value) {
    temcoreJNI.EnvData_y_vegs_set(swigCPtr, this, vegstate_env.getCPtr(value), value);
  }

  public vegstate_env getY_vegs() {
    long cPtr = temcoreJNI.EnvData_y_vegs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegstate_env(cPtr, false);
  }

  public void setY_snws(snwstate_env value) {
    temcoreJNI.EnvData_y_snws_set(swigCPtr, this, snwstate_env.getCPtr(value), value);
  }

  public snwstate_env getY_snws() {
    long cPtr = temcoreJNI.EnvData_y_snws_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwstate_env(cPtr, false);
  }

  public void setY_sois(soistate_env value) {
    temcoreJNI.EnvData_y_sois_set(swigCPtr, this, soistate_env.getCPtr(value), value);
  }

  public soistate_env getY_sois() {
    long cPtr = temcoreJNI.EnvData_y_sois_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soistate_env(cPtr, false);
  }

  public void setY_atmd(atmdiag_env value) {
    temcoreJNI.EnvData_y_atmd_set(swigCPtr, this, atmdiag_env.getCPtr(value), value);
  }

  public atmdiag_env getY_atmd() {
    long cPtr = temcoreJNI.EnvData_y_atmd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atmdiag_env(cPtr, false);
  }

  public void setY_vegd(vegdiag_env value) {
    temcoreJNI.EnvData_y_vegd_set(swigCPtr, this, vegdiag_env.getCPtr(value), value);
  }

  public vegdiag_env getY_vegd() {
    long cPtr = temcoreJNI.EnvData_y_vegd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new vegdiag_env(cPtr, false);
  }

  public void setY_snwd(snwdiag_env value) {
    temcoreJNI.EnvData_y_snwd_set(swigCPtr, this, snwdiag_env.getCPtr(value), value);
  }

  public snwdiag_env getY_snwd() {
    long cPtr = temcoreJNI.EnvData_y_snwd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snwdiag_env(cPtr, false);
  }

  public void setY_soid(soidiag_env value) {
    temcoreJNI.EnvData_y_soid_set(swigCPtr, this, soidiag_env.getCPtr(value), value);
  }

  public soidiag_env getY_soid() {
    long cPtr = temcoreJNI.EnvData_y_soid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soidiag_env(cPtr, false);
  }

  public void setY_l2a(lnd2atm_env value) {
    temcoreJNI.EnvData_y_l2a_set(swigCPtr, this, lnd2atm_env.getCPtr(value), value);
  }

  public lnd2atm_env getY_l2a() {
    long cPtr = temcoreJNI.EnvData_y_l2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new lnd2atm_env(cPtr, false);
  }

  public void setY_a2l(atm2lnd_env value) {
    temcoreJNI.EnvData_y_a2l_set(swigCPtr, this, atm2lnd_env.getCPtr(value), value);
  }

  public atm2lnd_env getY_a2l() {
    long cPtr = temcoreJNI.EnvData_y_a2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2lnd_env(cPtr, false);
  }

  public void setY_a2v(atm2veg_env value) {
    temcoreJNI.EnvData_y_a2v_set(swigCPtr, this, atm2veg_env.getCPtr(value), value);
  }

  public atm2veg_env getY_a2v() {
    long cPtr = temcoreJNI.EnvData_y_a2v_get(swigCPtr, this);
    return (cPtr == 0) ? null : new atm2veg_env(cPtr, false);
  }

  public void setY_v2a(veg2atm_env value) {
    temcoreJNI.EnvData_y_v2a_set(swigCPtr, this, veg2atm_env.getCPtr(value), value);
  }

  public veg2atm_env getY_v2a() {
    long cPtr = temcoreJNI.EnvData_y_v2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2atm_env(cPtr, false);
  }

  public void setY_v2g(veg2gnd_env value) {
    temcoreJNI.EnvData_y_v2g_set(swigCPtr, this, veg2gnd_env.getCPtr(value), value);
  }

  public veg2gnd_env getY_v2g() {
    long cPtr = temcoreJNI.EnvData_y_v2g_get(swigCPtr, this);
    return (cPtr == 0) ? null : new veg2gnd_env(cPtr, false);
  }

  public void setY_soi2l(soi2lnd_env value) {
    temcoreJNI.EnvData_y_soi2l_set(swigCPtr, this, soi2lnd_env.getCPtr(value), value);
  }

  public soi2lnd_env getY_soi2l() {
    long cPtr = temcoreJNI.EnvData_y_soi2l_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2lnd_env(cPtr, false);
  }

  public void setY_soi2a(soi2atm_env value) {
    temcoreJNI.EnvData_y_soi2a_set(swigCPtr, this, soi2atm_env.getCPtr(value), value);
  }

  public soi2atm_env getY_soi2a() {
    long cPtr = temcoreJNI.EnvData_y_soi2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new soi2atm_env(cPtr, false);
  }

  public void setY_snw2a(snw2atm_env value) {
    temcoreJNI.EnvData_y_snw2a_set(swigCPtr, this, snw2atm_env.getCPtr(value), value);
  }

  public snw2atm_env getY_snw2a() {
    long cPtr = temcoreJNI.EnvData_y_snw2a_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2atm_env(cPtr, false);
  }

  public void setY_snw2soi(snw2soi_env value) {
    temcoreJNI.EnvData_y_snw2soi_set(swigCPtr, this, snw2soi_env.getCPtr(value), value);
  }

  public snw2soi_env getY_snw2soi() {
    long cPtr = temcoreJNI.EnvData_y_snw2soi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new snw2soi_env(cPtr, false);
  }

  public void setMonthsfrozen(double value) {
    temcoreJNI.EnvData_monthsfrozen_set(swigCPtr, this, value);
  }

  public double getMonthsfrozen() {
    return temcoreJNI.EnvData_monthsfrozen_get(swigCPtr, this);
  }

  public void setRtfrozendays(int value) {
    temcoreJNI.EnvData_rtfrozendays_set(swigCPtr, this, value);
  }

  public int getRtfrozendays() {
    return temcoreJNI.EnvData_rtfrozendays_get(swigCPtr, this);
  }

  public void setRtunfrozendays(int value) {
    temcoreJNI.EnvData_rtunfrozendays_set(swigCPtr, this, value);
  }

  public int getRtunfrozendays() {
    return temcoreJNI.EnvData_rtunfrozendays_get(swigCPtr, this);
  }

  public void setCd(CohortData value) {
    temcoreJNI.EnvData_cd_set(swigCPtr, this, CohortData.getCPtr(value), value);
  }

  public CohortData getCd() {
    long cPtr = temcoreJNI.EnvData_cd_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CohortData(cPtr, false);
  }

  public void atm_beginOfYear() {
    temcoreJNI.EnvData_atm_beginOfYear(swigCPtr, this);
  }

  public void veg_beginOfYear() {
    temcoreJNI.EnvData_veg_beginOfYear(swigCPtr, this);
  }

  public void grnd_beginOfYear() {
    temcoreJNI.EnvData_grnd_beginOfYear(swigCPtr, this);
  }

  public void atm_beginOfMonth() {
    temcoreJNI.EnvData_atm_beginOfMonth(swigCPtr, this);
  }

  public void veg_beginOfMonth() {
    temcoreJNI.EnvData_veg_beginOfMonth(swigCPtr, this);
  }

  public void grnd_beginOfMonth() {
    temcoreJNI.EnvData_grnd_beginOfMonth(swigCPtr, this);
  }

  public void grnd_beginOfDay() {
    temcoreJNI.EnvData_grnd_beginOfDay(swigCPtr, this);
  }

  public void atm_endOfDay(int dinm) {
    temcoreJNI.EnvData_atm_endOfDay(swigCPtr, this, dinm);
  }

  public void veg_endOfDay(int dinm) {
    temcoreJNI.EnvData_veg_endOfDay(swigCPtr, this, dinm);
  }

  public void grnd_endOfDay(int dinm, int doy) {
    temcoreJNI.EnvData_grnd_endOfDay(swigCPtr, this, dinm, doy);
  }

  public void atm_endOfMonth() {
    temcoreJNI.EnvData_atm_endOfMonth(swigCPtr, this);
  }

  public void veg_endOfMonth(int currmind) {
    temcoreJNI.EnvData_veg_endOfMonth(swigCPtr, this, currmind);
  }

  public void grnd_endOfMonth() {
    temcoreJNI.EnvData_grnd_endOfMonth(swigCPtr, this);
  }

}
