/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class GridData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GridData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_GridData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GridData() {
    this(temcoreJNI.new_GridData(), true);
  }

  public void clear() {
    temcoreJNI.GridData_clear(swigCPtr, this);
  }

  public void setLat(float value) {
    temcoreJNI.GridData_lat_set(swigCPtr, this, value);
  }

  public float getLat() {
    return temcoreJNI.GridData_lat_get(swigCPtr, this);
  }

  public void setLon(float value) {
    temcoreJNI.GridData_lon_set(swigCPtr, this, value);
  }

  public float getLon() {
    return temcoreJNI.GridData_lon_get(swigCPtr, this);
  }

  public void setAlldaylengths(float[] value) {
    temcoreJNI.GridData_alldaylengths_set(swigCPtr, this, value);
  }

  public float[] getAlldaylengths() {
    return temcoreJNI.GridData_alldaylengths_get(swigCPtr, this);
  }

  public void setDrgtype(int value) {
    temcoreJNI.GridData_drgtype_set(swigCPtr, this, value);
  }

  public int getDrgtype() {
    return temcoreJNI.GridData_drgtype_get(swigCPtr, this);
  }

  public void setTopsoil(int value) {
    temcoreJNI.GridData_topsoil_set(swigCPtr, this, value);
  }

  public int getTopsoil() {
    return temcoreJNI.GridData_topsoil_get(swigCPtr, this);
  }

  public void setBotsoil(int value) {
    temcoreJNI.GridData_botsoil_set(swigCPtr, this, value);
  }

  public int getBotsoil() {
    return temcoreJNI.GridData_botsoil_get(swigCPtr, this);
  }

  public void setFri(int value) {
    temcoreJNI.GridData_fri_set(swigCPtr, this, value);
  }

  public int getFri() {
    return temcoreJNI.GridData_fri_get(swigCPtr, this);
  }

  public void setPfsize(double[] value) {
    temcoreJNI.GridData_pfsize_set(swigCPtr, this, value);
  }

  public double[] getPfsize() {
    return temcoreJNI.GridData_pfsize_get(swigCPtr, this);
  }

  public void setPfseason(double[] value) {
    temcoreJNI.GridData_pfseason_set(swigCPtr, this, value);
  }

  public double[] getPfseason() {
    return temcoreJNI.GridData_pfseason_get(swigCPtr, this);
  }

}
