/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class OutDataRegn {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OutDataRegn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OutDataRegn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_OutDataRegn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OutDataRegn() {
    this(temcoreJNI.new_OutDataRegn(), true);
  }

  public void setChtid(int value) {
    temcoreJNI.OutDataRegn_chtid_set(swigCPtr, this, value);
  }

  public int getChtid() {
    return temcoreJNI.OutDataRegn_chtid_get(swigCPtr, this);
  }

  public void setYear(int value) {
    temcoreJNI.OutDataRegn_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return temcoreJNI.OutDataRegn_year_get(swigCPtr, this);
  }

  public void setYrsdist(int value) {
    temcoreJNI.OutDataRegn_yrsdist_set(swigCPtr, this, value);
  }

  public int getYrsdist() {
    return temcoreJNI.OutDataRegn_yrsdist_get(swigCPtr, this);
  }

  public void setOutvarlist(int[] value) {
    temcoreJNI.OutDataRegn_outvarlist_set(swigCPtr, this, value);
  }

  public int[] getOutvarlist() {
    return temcoreJNI.OutDataRegn_outvarlist_get(swigCPtr, this);
  }

  public void setStatus(SWIGTYPE_p_vectorT_int_t value) {
    temcoreJNI.OutDataRegn_status_set(swigCPtr, this, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_int_t getStatus() {
    return new SWIGTYPE_p_vectorT_int_t(temcoreJNI.OutDataRegn_status_get(swigCPtr, this), true);
  }

  public void setMonth(SWIGTYPE_p_vectorT_int_t value) {
    temcoreJNI.OutDataRegn_month_set(swigCPtr, this, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_int_t getMonth() {
    return new SWIGTYPE_p_vectorT_int_t(temcoreJNI.OutDataRegn_month_get(swigCPtr, this), true);
  }

  public void setDoy(SWIGTYPE_p_vectorT_int_t value) {
    temcoreJNI.OutDataRegn_doy_set(swigCPtr, this, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_int_t getDoy() {
    return new SWIGTYPE_p_vectorT_int_t(temcoreJNI.OutDataRegn_doy_get(swigCPtr, this), true);
  }

  public void setGrowstart(SWIGTYPE_p_vectorT_int_t value) {
    temcoreJNI.OutDataRegn_growstart_set(swigCPtr, this, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_int_t getGrowstart() {
    long cPtr = temcoreJNI.OutDataRegn_growstart_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_int_t(cPtr, false);
  }

  public void setGrowend(SWIGTYPE_p_vectorT_int_t value) {
    temcoreJNI.OutDataRegn_growend_set(swigCPtr, this, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_int_t getGrowend() {
    long cPtr = temcoreJNI.OutDataRegn_growend_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_int_t(cPtr, false);
  }

  public void setVegcov(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vegcov_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVegcov() {
    long cPtr = temcoreJNI.OutDataRegn_vegcov_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setVegage(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vegage_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVegage() {
    long cPtr = temcoreJNI.OutDataRegn_vegage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setLai(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_lai_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getLai() {
    long cPtr = temcoreJNI.OutDataRegn_lai_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setVegc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vegc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVegc() {
    long cPtr = temcoreJNI.OutDataRegn_vegc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setLeafc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_leafc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getLeafc() {
    long cPtr = temcoreJNI.OutDataRegn_leafc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setStemc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_stemc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getStemc() {
    long cPtr = temcoreJNI.OutDataRegn_stemc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setRootc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_rootc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getRootc() {
    long cPtr = temcoreJNI.OutDataRegn_rootc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setVegn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vegn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVegn() {
    long cPtr = temcoreJNI.OutDataRegn_vegn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setLabn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_labn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getLabn() {
    long cPtr = temcoreJNI.OutDataRegn_labn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setLeafn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_leafn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getLeafn() {
    long cPtr = temcoreJNI.OutDataRegn_leafn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setStemn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_stemn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getStemn() {
    long cPtr = temcoreJNI.OutDataRegn_stemn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setRootn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_rootn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getRootn() {
    long cPtr = temcoreJNI.OutDataRegn_rootn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setGpp(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_gpp_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getGpp() {
    long cPtr = temcoreJNI.OutDataRegn_gpp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setNpp(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_npp_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getNpp() {
    long cPtr = temcoreJNI.OutDataRegn_npp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setLtrfalc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ltrfalc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getLtrfalc() {
    long cPtr = temcoreJNI.OutDataRegn_ltrfalc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setLtrfaln(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ltrfaln_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getLtrfaln() {
    long cPtr = temcoreJNI.OutDataRegn_ltrfaln_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setNuptake(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_nuptake_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getNuptake() {
    long cPtr = temcoreJNI.OutDataRegn_nuptake_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vectorT_double_t(cPtr, false);
  }

  public void setPermafrost(SWIGTYPE_p_vectorT_int_t value) {
    temcoreJNI.OutDataRegn_permafrost_set(swigCPtr, this, SWIGTYPE_p_vectorT_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_int_t getPermafrost() {
    return new SWIGTYPE_p_vectorT_int_t(temcoreJNI.OutDataRegn_permafrost_get(swigCPtr, this), true);
  }

  public void setMossdz(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_mossdz_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMossdz() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_mossdz_get(swigCPtr, this), true);
  }

  public void setOshlwdz(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_oshlwdz_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOshlwdz() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_oshlwdz_get(swigCPtr, this), true);
  }

  public void setOdeepdz(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_odeepdz_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOdeepdz() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_odeepdz_get(swigCPtr, this), true);
  }

  public void setMineadz(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_mineadz_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMineadz() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_mineadz_get(swigCPtr, this), true);
  }

  public void setMinebdz(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_minebdz_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMinebdz() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_minebdz_get(swigCPtr, this), true);
  }

  public void setMinecdz(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_minecdz_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMinecdz() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_minecdz_get(swigCPtr, this), true);
  }

  public void setOshlwc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_oshlwc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOshlwc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_oshlwc_get(swigCPtr, this), true);
  }

  public void setOdeepc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_odeepc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOdeepc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_odeepc_get(swigCPtr, this), true);
  }

  public void setMineac(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_mineac_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMineac() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_mineac_get(swigCPtr, this), true);
  }

  public void setMinebc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_minebc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMinebc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_minebc_get(swigCPtr, this), true);
  }

  public void setMinecc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_minecc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getMinecc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_minecc_get(swigCPtr, this), true);
  }

  public void setOrgn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_orgn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOrgn() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_orgn_get(swigCPtr, this), true);
  }

  public void setAvln(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_avln_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getAvln() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_avln_get(swigCPtr, this), true);
  }

  public void setCh4(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4_get(swigCPtr, this), true);
  }

  public void setRh(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_rh_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getRh() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_rh_get(swigCPtr, this), true);
  }

  public void setCh4prod(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4prod_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4prod() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4prod_get(swigCPtr, this), true);
  }

  public void setCh4oxid(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4oxid_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4oxid() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4oxid_get(swigCPtr, this), true);
  }

  public void setCh4flux(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4flux_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4flux() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4flux_get(swigCPtr, this), true);
  }

  public void setCh4flux2a(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4flux2a_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4flux2a() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4flux2a_get(swigCPtr, this), true);
  }

  public void setCh4flux2p(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4flux2p_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4flux2p() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4flux2p_get(swigCPtr, this), true);
  }

  public void setCh4flux2b(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ch4flux2b_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getCh4flux2b() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ch4flux2b_get(swigCPtr, this), true);
  }

  public void setNetnmin(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_netnmin_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getNetnmin() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_netnmin_get(swigCPtr, this), true);
  }

  public void setOrgninput(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_orgninput_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOrgninput() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_orgninput_get(swigCPtr, this), true);
  }

  public void setAvlninput(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_avlninput_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getAvlninput() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_avlninput_get(swigCPtr, this), true);
  }

  public void setDoclost(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_doclost_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getDoclost() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_doclost_get(swigCPtr, this), true);
  }

  public void setOrgnlost(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_orgnlost_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getOrgnlost() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_orgnlost_get(swigCPtr, this), true);
  }

  public void setAvlnlost(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_avlnlost_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getAvlnlost() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_avlnlost_get(swigCPtr, this), true);
  }

  public void setEet(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_eet_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getEet() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_eet_get(swigCPtr, this), true);
  }

  public void setPet(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_pet_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getPet() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_pet_get(swigCPtr, this), true);
  }

  public void setQinfl(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_qinfl_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getQinfl() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_qinfl_get(swigCPtr, this), true);
  }

  public void setQdrain(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_qdrain_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getQdrain() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_qdrain_get(swigCPtr, this), true);
  }

  public void setQrunoff(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_qrunoff_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getQrunoff() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_qrunoff_get(swigCPtr, this), true);
  }

  public void setSnwthick(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_snwthick_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getSnwthick() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_snwthick_get(swigCPtr, this), true);
  }

  public void setSwe(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_swe_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getSwe() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_swe_get(swigCPtr, this), true);
  }

  public void setWtd(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_wtd_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getWtd() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_wtd_get(swigCPtr, this), true);
  }

  public void setAlc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_alc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getAlc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_alc_get(swigCPtr, this), true);
  }

  public void setAld(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_ald_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getAld() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_ald_get(swigCPtr, this), true);
  }

  public void setVwcshlw(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vwcshlw_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVwcshlw() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_vwcshlw_get(swigCPtr, this), true);
  }

  public void setVwcdeep(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vwcdeep_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVwcdeep() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_vwcdeep_get(swigCPtr, this), true);
  }

  public void setVwcminea(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vwcminea_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVwcminea() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_vwcminea_get(swigCPtr, this), true);
  }

  public void setVwcmineb(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vwcmineb_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVwcmineb() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_vwcmineb_get(swigCPtr, this), true);
  }

  public void setVwcminec(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_vwcminec_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getVwcminec() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_vwcminec_get(swigCPtr, this), true);
  }

  public void setTshlw(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tshlw_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTshlw() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tshlw_get(swigCPtr, this), true);
  }

  public void setTdeep(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tdeep_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTdeep() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tdeep_get(swigCPtr, this), true);
  }

  public void setTminea(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tminea_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTminea() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tminea_get(swigCPtr, this), true);
  }

  public void setTmineb(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tmineb_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTmineb() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tmineb_get(swigCPtr, this), true);
  }

  public void setTminec(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tminec_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTminec() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tminec_get(swigCPtr, this), true);
  }

  public void setHkshlw(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_hkshlw_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getHkshlw() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_hkshlw_get(swigCPtr, this), true);
  }

  public void setHkdeep(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_hkdeep_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getHkdeep() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_hkdeep_get(swigCPtr, this), true);
  }

  public void setHkminea(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_hkminea_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getHkminea() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_hkminea_get(swigCPtr, this), true);
  }

  public void setHkmineb(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_hkmineb_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getHkmineb() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_hkmineb_get(swigCPtr, this), true);
  }

  public void setHkminec(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_hkminec_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getHkminec() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_hkminec_get(swigCPtr, this), true);
  }

  public void setTcshlw(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tcshlw_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTcshlw() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tcshlw_get(swigCPtr, this), true);
  }

  public void setTcdeep(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tcdeep_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTcdeep() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tcdeep_get(swigCPtr, this), true);
  }

  public void setTcminea(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tcminea_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTcminea() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tcminea_get(swigCPtr, this), true);
  }

  public void setTcmineb(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tcmineb_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTcmineb() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tcmineb_get(swigCPtr, this), true);
  }

  public void setTcminec(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tcminec_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTcminec() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tcminec_get(swigCPtr, this), true);
  }

  public void setTbotrock(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_tbotrock_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getTbotrock() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_tbotrock_get(swigCPtr, this), true);
  }

  public void setBurnthick(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnthick_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnthick() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnthick_get(swigCPtr, this), true);
  }

  public void setBurnsoic(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnsoic_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnsoic() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnsoic_get(swigCPtr, this), true);
  }

  public void setBurnvegc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnvegc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnvegc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnvegc_get(swigCPtr, this), true);
  }

  public void setBurnsoin(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnsoin_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnsoin() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnsoin_get(swigCPtr, this), true);
  }

  public void setBurnvegn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnvegn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnvegn() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnvegn_get(swigCPtr, this), true);
  }

  public void setBurnretainc(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnretainc_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnretainc() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnretainc_get(swigCPtr, this), true);
  }

  public void setBurnretainn(SWIGTYPE_p_vectorT_double_t value) {
    temcoreJNI.OutDataRegn_burnretainn_set(swigCPtr, this, SWIGTYPE_p_vectorT_double_t.getCPtr(value));
  }

  public SWIGTYPE_p_vectorT_double_t getBurnretainn() {
    return new SWIGTYPE_p_vectorT_double_t(temcoreJNI.OutDataRegn_burnretainn_get(swigCPtr, this), true);
  }

}
