/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class OutDataRegn {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OutDataRegn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OutDataRegn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_OutDataRegn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OutDataRegn() {
    this(temcoreJNI.new_OutDataRegn(), true);
  }

  public void setChtid(int value) {
    temcoreJNI.OutDataRegn_chtid_set(swigCPtr, this, value);
  }

  public int getChtid() {
    return temcoreJNI.OutDataRegn_chtid_get(swigCPtr, this);
  }

  public void setStatus(int[] value) {
    temcoreJNI.OutDataRegn_status_set(swigCPtr, this, value);
  }

  public int[] getStatus() {
    return temcoreJNI.OutDataRegn_status_get(swigCPtr, this);
  }

  public void setYear(int value) {
    temcoreJNI.OutDataRegn_year_set(swigCPtr, this, value);
  }

  public int getYear() {
    return temcoreJNI.OutDataRegn_year_get(swigCPtr, this);
  }

  public void setMonth(int[] value) {
    temcoreJNI.OutDataRegn_month_set(swigCPtr, this, value);
  }

  public int[] getMonth() {
    return temcoreJNI.OutDataRegn_month_get(swigCPtr, this);
  }

  public void setYrsdist(int value) {
    temcoreJNI.OutDataRegn_yrsdist_set(swigCPtr, this, value);
  }

  public int getYrsdist() {
    return temcoreJNI.OutDataRegn_yrsdist_get(swigCPtr, this);
  }

  public void setOutvarlist(int[] value) {
    temcoreJNI.OutDataRegn_outvarlist_set(swigCPtr, this, value);
  }

  public int[] getOutvarlist() {
    return temcoreJNI.OutDataRegn_outvarlist_get(swigCPtr, this);
  }

  public void setGrowstart(SWIGTYPE_p_a_NUM_PFT__int value) {
    temcoreJNI.OutDataRegn_growstart_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__int getGrowstart() {
    long cPtr = temcoreJNI.OutDataRegn_growstart_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__int(cPtr, false);
  }

  public void setGrowend(SWIGTYPE_p_a_NUM_PFT__int value) {
    temcoreJNI.OutDataRegn_growend_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__int getGrowend() {
    long cPtr = temcoreJNI.OutDataRegn_growend_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__int(cPtr, false);
  }

  public void setVegcov(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_vegcov_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getVegcov() {
    long cPtr = temcoreJNI.OutDataRegn_vegcov_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setVegage(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_vegage_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getVegage() {
    long cPtr = temcoreJNI.OutDataRegn_vegage_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setLai(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_lai_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getLai() {
    long cPtr = temcoreJNI.OutDataRegn_lai_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setVegc(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_vegc_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getVegc() {
    long cPtr = temcoreJNI.OutDataRegn_vegc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setLeafc(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_leafc_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getLeafc() {
    long cPtr = temcoreJNI.OutDataRegn_leafc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setStemc(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_stemc_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getStemc() {
    long cPtr = temcoreJNI.OutDataRegn_stemc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setRootc(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_rootc_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getRootc() {
    long cPtr = temcoreJNI.OutDataRegn_rootc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setVegn(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_vegn_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getVegn() {
    long cPtr = temcoreJNI.OutDataRegn_vegn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setLabn(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_labn_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getLabn() {
    long cPtr = temcoreJNI.OutDataRegn_labn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setLeafn(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_leafn_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getLeafn() {
    long cPtr = temcoreJNI.OutDataRegn_leafn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setStemn(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_stemn_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getStemn() {
    long cPtr = temcoreJNI.OutDataRegn_stemn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setRootn(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_rootn_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getRootn() {
    long cPtr = temcoreJNI.OutDataRegn_rootn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setGpp(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_gpp_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getGpp() {
    long cPtr = temcoreJNI.OutDataRegn_gpp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setNpp(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_npp_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getNpp() {
    long cPtr = temcoreJNI.OutDataRegn_npp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setLtrfalc(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_ltrfalc_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getLtrfalc() {
    long cPtr = temcoreJNI.OutDataRegn_ltrfalc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setLtrfaln(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_ltrfaln_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getLtrfaln() {
    long cPtr = temcoreJNI.OutDataRegn_ltrfaln_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setNuptake(SWIGTYPE_p_a_NUM_PFT__double value) {
    temcoreJNI.OutDataRegn_nuptake_set(swigCPtr, this, SWIGTYPE_p_a_NUM_PFT__double.getCPtr(value));
  }

  public SWIGTYPE_p_a_NUM_PFT__double getNuptake() {
    long cPtr = temcoreJNI.OutDataRegn_nuptake_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_NUM_PFT__double(cPtr, false);
  }

  public void setPermafrost(int[] value) {
    temcoreJNI.OutDataRegn_permafrost_set(swigCPtr, this, value);
  }

  public int[] getPermafrost() {
    return temcoreJNI.OutDataRegn_permafrost_get(swigCPtr, this);
  }

  public void setMossdz(double[] value) {
    temcoreJNI.OutDataRegn_mossdz_set(swigCPtr, this, value);
  }

  public double[] getMossdz() {
    return temcoreJNI.OutDataRegn_mossdz_get(swigCPtr, this);
  }

  public void setOshlwdz(double[] value) {
    temcoreJNI.OutDataRegn_oshlwdz_set(swigCPtr, this, value);
  }

  public double[] getOshlwdz() {
    return temcoreJNI.OutDataRegn_oshlwdz_get(swigCPtr, this);
  }

  public void setOdeepdz(double[] value) {
    temcoreJNI.OutDataRegn_odeepdz_set(swigCPtr, this, value);
  }

  public double[] getOdeepdz() {
    return temcoreJNI.OutDataRegn_odeepdz_get(swigCPtr, this);
  }

  public void setMineadz(double[] value) {
    temcoreJNI.OutDataRegn_mineadz_set(swigCPtr, this, value);
  }

  public double[] getMineadz() {
    return temcoreJNI.OutDataRegn_mineadz_get(swigCPtr, this);
  }

  public void setMinebdz(double[] value) {
    temcoreJNI.OutDataRegn_minebdz_set(swigCPtr, this, value);
  }

  public double[] getMinebdz() {
    return temcoreJNI.OutDataRegn_minebdz_get(swigCPtr, this);
  }

  public void setMinecdz(double[] value) {
    temcoreJNI.OutDataRegn_minecdz_set(swigCPtr, this, value);
  }

  public double[] getMinecdz() {
    return temcoreJNI.OutDataRegn_minecdz_get(swigCPtr, this);
  }

  public void setOshlwc(double[] value) {
    temcoreJNI.OutDataRegn_oshlwc_set(swigCPtr, this, value);
  }

  public double[] getOshlwc() {
    return temcoreJNI.OutDataRegn_oshlwc_get(swigCPtr, this);
  }

  public void setOdeepc(double[] value) {
    temcoreJNI.OutDataRegn_odeepc_set(swigCPtr, this, value);
  }

  public double[] getOdeepc() {
    return temcoreJNI.OutDataRegn_odeepc_get(swigCPtr, this);
  }

  public void setMineac(double[] value) {
    temcoreJNI.OutDataRegn_mineac_set(swigCPtr, this, value);
  }

  public double[] getMineac() {
    return temcoreJNI.OutDataRegn_mineac_get(swigCPtr, this);
  }

  public void setMinebc(double[] value) {
    temcoreJNI.OutDataRegn_minebc_set(swigCPtr, this, value);
  }

  public double[] getMinebc() {
    return temcoreJNI.OutDataRegn_minebc_get(swigCPtr, this);
  }

  public void setMinecc(double[] value) {
    temcoreJNI.OutDataRegn_minecc_set(swigCPtr, this, value);
  }

  public double[] getMinecc() {
    return temcoreJNI.OutDataRegn_minecc_get(swigCPtr, this);
  }

  public void setOrgn(double[] value) {
    temcoreJNI.OutDataRegn_orgn_set(swigCPtr, this, value);
  }

  public double[] getOrgn() {
    return temcoreJNI.OutDataRegn_orgn_get(swigCPtr, this);
  }

  public void setAvln(double[] value) {
    temcoreJNI.OutDataRegn_avln_set(swigCPtr, this, value);
  }

  public double[] getAvln() {
    return temcoreJNI.OutDataRegn_avln_get(swigCPtr, this);
  }

  public void setRh(double[] value) {
    temcoreJNI.OutDataRegn_rh_set(swigCPtr, this, value);
  }

  public double[] getRh() {
    return temcoreJNI.OutDataRegn_rh_get(swigCPtr, this);
  }

  public void setNetnmin(double[] value) {
    temcoreJNI.OutDataRegn_netnmin_set(swigCPtr, this, value);
  }

  public double[] getNetnmin() {
    return temcoreJNI.OutDataRegn_netnmin_get(swigCPtr, this);
  }

  public void setOrgninput(double[] value) {
    temcoreJNI.OutDataRegn_orgninput_set(swigCPtr, this, value);
  }

  public double[] getOrgninput() {
    return temcoreJNI.OutDataRegn_orgninput_get(swigCPtr, this);
  }

  public void setAvlninput(double[] value) {
    temcoreJNI.OutDataRegn_avlninput_set(swigCPtr, this, value);
  }

  public double[] getAvlninput() {
    return temcoreJNI.OutDataRegn_avlninput_get(swigCPtr, this);
  }

  public void setDoclost(double[] value) {
    temcoreJNI.OutDataRegn_doclost_set(swigCPtr, this, value);
  }

  public double[] getDoclost() {
    return temcoreJNI.OutDataRegn_doclost_get(swigCPtr, this);
  }

  public void setOrgnlost(double[] value) {
    temcoreJNI.OutDataRegn_orgnlost_set(swigCPtr, this, value);
  }

  public double[] getOrgnlost() {
    return temcoreJNI.OutDataRegn_orgnlost_get(swigCPtr, this);
  }

  public void setAvlnlost(double[] value) {
    temcoreJNI.OutDataRegn_avlnlost_set(swigCPtr, this, value);
  }

  public double[] getAvlnlost() {
    return temcoreJNI.OutDataRegn_avlnlost_get(swigCPtr, this);
  }

  public void setEet(double[] value) {
    temcoreJNI.OutDataRegn_eet_set(swigCPtr, this, value);
  }

  public double[] getEet() {
    return temcoreJNI.OutDataRegn_eet_get(swigCPtr, this);
  }

  public void setPet(double[] value) {
    temcoreJNI.OutDataRegn_pet_set(swigCPtr, this, value);
  }

  public double[] getPet() {
    return temcoreJNI.OutDataRegn_pet_get(swigCPtr, this);
  }

  public void setQinfl(double[] value) {
    temcoreJNI.OutDataRegn_qinfl_set(swigCPtr, this, value);
  }

  public double[] getQinfl() {
    return temcoreJNI.OutDataRegn_qinfl_get(swigCPtr, this);
  }

  public void setQdrain(double[] value) {
    temcoreJNI.OutDataRegn_qdrain_set(swigCPtr, this, value);
  }

  public double[] getQdrain() {
    return temcoreJNI.OutDataRegn_qdrain_get(swigCPtr, this);
  }

  public void setQrunoff(double[] value) {
    temcoreJNI.OutDataRegn_qrunoff_set(swigCPtr, this, value);
  }

  public double[] getQrunoff() {
    return temcoreJNI.OutDataRegn_qrunoff_get(swigCPtr, this);
  }

  public void setSnwthick(double[] value) {
    temcoreJNI.OutDataRegn_snwthick_set(swigCPtr, this, value);
  }

  public double[] getSnwthick() {
    return temcoreJNI.OutDataRegn_snwthick_get(swigCPtr, this);
  }

  public void setSwe(double[] value) {
    temcoreJNI.OutDataRegn_swe_set(swigCPtr, this, value);
  }

  public double[] getSwe() {
    return temcoreJNI.OutDataRegn_swe_get(swigCPtr, this);
  }

  public void setWtd(double[] value) {
    temcoreJNI.OutDataRegn_wtd_set(swigCPtr, this, value);
  }

  public double[] getWtd() {
    return temcoreJNI.OutDataRegn_wtd_get(swigCPtr, this);
  }

  public void setAlc(double[] value) {
    temcoreJNI.OutDataRegn_alc_set(swigCPtr, this, value);
  }

  public double[] getAlc() {
    return temcoreJNI.OutDataRegn_alc_get(swigCPtr, this);
  }

  public void setAld(double[] value) {
    temcoreJNI.OutDataRegn_ald_set(swigCPtr, this, value);
  }

  public double[] getAld() {
    return temcoreJNI.OutDataRegn_ald_get(swigCPtr, this);
  }

  public void setVwcshlw(double[] value) {
    temcoreJNI.OutDataRegn_vwcshlw_set(swigCPtr, this, value);
  }

  public double[] getVwcshlw() {
    return temcoreJNI.OutDataRegn_vwcshlw_get(swigCPtr, this);
  }

  public void setVwcdeep(double[] value) {
    temcoreJNI.OutDataRegn_vwcdeep_set(swigCPtr, this, value);
  }

  public double[] getVwcdeep() {
    return temcoreJNI.OutDataRegn_vwcdeep_get(swigCPtr, this);
  }

  public void setVwcminea(double[] value) {
    temcoreJNI.OutDataRegn_vwcminea_set(swigCPtr, this, value);
  }

  public double[] getVwcminea() {
    return temcoreJNI.OutDataRegn_vwcminea_get(swigCPtr, this);
  }

  public void setVwcmineb(double[] value) {
    temcoreJNI.OutDataRegn_vwcmineb_set(swigCPtr, this, value);
  }

  public double[] getVwcmineb() {
    return temcoreJNI.OutDataRegn_vwcmineb_get(swigCPtr, this);
  }

  public void setVwcminec(double[] value) {
    temcoreJNI.OutDataRegn_vwcminec_set(swigCPtr, this, value);
  }

  public double[] getVwcminec() {
    return temcoreJNI.OutDataRegn_vwcminec_get(swigCPtr, this);
  }

  public void setTshlw(double[] value) {
    temcoreJNI.OutDataRegn_tshlw_set(swigCPtr, this, value);
  }

  public double[] getTshlw() {
    return temcoreJNI.OutDataRegn_tshlw_get(swigCPtr, this);
  }

  public void setTdeep(double[] value) {
    temcoreJNI.OutDataRegn_tdeep_set(swigCPtr, this, value);
  }

  public double[] getTdeep() {
    return temcoreJNI.OutDataRegn_tdeep_get(swigCPtr, this);
  }

  public void setTminea(double[] value) {
    temcoreJNI.OutDataRegn_tminea_set(swigCPtr, this, value);
  }

  public double[] getTminea() {
    return temcoreJNI.OutDataRegn_tminea_get(swigCPtr, this);
  }

  public void setTmineb(double[] value) {
    temcoreJNI.OutDataRegn_tmineb_set(swigCPtr, this, value);
  }

  public double[] getTmineb() {
    return temcoreJNI.OutDataRegn_tmineb_get(swigCPtr, this);
  }

  public void setTminec(double[] value) {
    temcoreJNI.OutDataRegn_tminec_set(swigCPtr, this, value);
  }

  public double[] getTminec() {
    return temcoreJNI.OutDataRegn_tminec_get(swigCPtr, this);
  }

  public void setHkshlw(double[] value) {
    temcoreJNI.OutDataRegn_hkshlw_set(swigCPtr, this, value);
  }

  public double[] getHkshlw() {
    return temcoreJNI.OutDataRegn_hkshlw_get(swigCPtr, this);
  }

  public void setHkdeep(double[] value) {
    temcoreJNI.OutDataRegn_hkdeep_set(swigCPtr, this, value);
  }

  public double[] getHkdeep() {
    return temcoreJNI.OutDataRegn_hkdeep_get(swigCPtr, this);
  }

  public void setHkminea(double[] value) {
    temcoreJNI.OutDataRegn_hkminea_set(swigCPtr, this, value);
  }

  public double[] getHkminea() {
    return temcoreJNI.OutDataRegn_hkminea_get(swigCPtr, this);
  }

  public void setHkmineb(double[] value) {
    temcoreJNI.OutDataRegn_hkmineb_set(swigCPtr, this, value);
  }

  public double[] getHkmineb() {
    return temcoreJNI.OutDataRegn_hkmineb_get(swigCPtr, this);
  }

  public void setHkminec(double[] value) {
    temcoreJNI.OutDataRegn_hkminec_set(swigCPtr, this, value);
  }

  public double[] getHkminec() {
    return temcoreJNI.OutDataRegn_hkminec_get(swigCPtr, this);
  }

  public void setTcshlw(double[] value) {
    temcoreJNI.OutDataRegn_tcshlw_set(swigCPtr, this, value);
  }

  public double[] getTcshlw() {
    return temcoreJNI.OutDataRegn_tcshlw_get(swigCPtr, this);
  }

  public void setTcdeep(double[] value) {
    temcoreJNI.OutDataRegn_tcdeep_set(swigCPtr, this, value);
  }

  public double[] getTcdeep() {
    return temcoreJNI.OutDataRegn_tcdeep_get(swigCPtr, this);
  }

  public void setTcminea(double[] value) {
    temcoreJNI.OutDataRegn_tcminea_set(swigCPtr, this, value);
  }

  public double[] getTcminea() {
    return temcoreJNI.OutDataRegn_tcminea_get(swigCPtr, this);
  }

  public void setTcmineb(double[] value) {
    temcoreJNI.OutDataRegn_tcmineb_set(swigCPtr, this, value);
  }

  public double[] getTcmineb() {
    return temcoreJNI.OutDataRegn_tcmineb_get(swigCPtr, this);
  }

  public void setTcminec(double[] value) {
    temcoreJNI.OutDataRegn_tcminec_set(swigCPtr, this, value);
  }

  public double[] getTcminec() {
    return temcoreJNI.OutDataRegn_tcminec_get(swigCPtr, this);
  }

  public void setTbotrock(double[] value) {
    temcoreJNI.OutDataRegn_tbotrock_set(swigCPtr, this, value);
  }

  public double[] getTbotrock() {
    return temcoreJNI.OutDataRegn_tbotrock_get(swigCPtr, this);
  }

  public void setBurnthick(double[] value) {
    temcoreJNI.OutDataRegn_burnthick_set(swigCPtr, this, value);
  }

  public double[] getBurnthick() {
    return temcoreJNI.OutDataRegn_burnthick_get(swigCPtr, this);
  }

  public void setBurnsoic(double[] value) {
    temcoreJNI.OutDataRegn_burnsoic_set(swigCPtr, this, value);
  }

  public double[] getBurnsoic() {
    return temcoreJNI.OutDataRegn_burnsoic_get(swigCPtr, this);
  }

  public void setBurnvegc(double[] value) {
    temcoreJNI.OutDataRegn_burnvegc_set(swigCPtr, this, value);
  }

  public double[] getBurnvegc() {
    return temcoreJNI.OutDataRegn_burnvegc_get(swigCPtr, this);
  }

  public void setBurnsoin(double[] value) {
    temcoreJNI.OutDataRegn_burnsoin_set(swigCPtr, this, value);
  }

  public double[] getBurnsoin() {
    return temcoreJNI.OutDataRegn_burnsoin_get(swigCPtr, this);
  }

  public void setBurnvegn(double[] value) {
    temcoreJNI.OutDataRegn_burnvegn_set(swigCPtr, this, value);
  }

  public double[] getBurnvegn() {
    return temcoreJNI.OutDataRegn_burnvegn_get(swigCPtr, this);
  }

  public void setBurnretainc(double[] value) {
    temcoreJNI.OutDataRegn_burnretainc_set(swigCPtr, this, value);
  }

  public double[] getBurnretainc() {
    return temcoreJNI.OutDataRegn_burnretainc_get(swigCPtr, this);
  }

  public void setBurnretainn(double[] value) {
    temcoreJNI.OutDataRegn_burnretainn_set(swigCPtr, this, value);
  }

  public double[] getBurnretainn() {
    return temcoreJNI.OutDataRegn_burnretainn_get(swigCPtr, this);
  }

}
