/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class OutRetrive {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OutRetrive(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OutRetrive obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_OutRetrive(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OutRetrive() {
    this(temcoreJNI.new_OutRetrive(), true);
  }

  public void setCohortcount(int value) {
    temcoreJNI.OutRetrive_cohortcount_set(swigCPtr, this, value);
  }

  public int getCohortcount() {
    return temcoreJNI.OutRetrive_cohortcount_get(swigCPtr, this);
  }

  public void setEnvoddly(SWIGTYPE_p_a_31__oneenv value) {
    temcoreJNI.OutRetrive_envoddly_set(swigCPtr, this, SWIGTYPE_p_a_31__oneenv.getCPtr(value));
  }

  public SWIGTYPE_p_a_31__oneenv getEnvoddly() {
    long cPtr = temcoreJNI.OutRetrive_envoddly_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_31__oneenv(cPtr, false);
  }

  public void setEnvoddlyall(SWIGTYPE_p_oneenv value) {
    temcoreJNI.OutRetrive_envoddlyall_set(swigCPtr, this, SWIGTYPE_p_oneenv.getCPtr(value));
  }

  public SWIGTYPE_p_oneenv getEnvoddlyall() {
    long cPtr = temcoreJNI.OutRetrive_envoddlyall_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_oneenv(cPtr, false);
  }

  public void setBgcoddly(SWIGTYPE_p_a_31__onebgc value) {
    temcoreJNI.OutRetrive_bgcoddly_set(swigCPtr, this, SWIGTYPE_p_a_31__onebgc.getCPtr(value));
  }

  public SWIGTYPE_p_a_31__onebgc getBgcoddly() {
    long cPtr = temcoreJNI.OutRetrive_bgcoddly_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_31__onebgc(cPtr, false);
  }

  public void setBgcoddlyall(SWIGTYPE_p_onebgc value) {
    temcoreJNI.OutRetrive_bgcoddlyall_set(swigCPtr, this, SWIGTYPE_p_onebgc.getCPtr(value));
  }

  public SWIGTYPE_p_onebgc getBgcoddlyall() {
    long cPtr = temcoreJNI.OutRetrive_bgcoddlyall_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_onebgc(cPtr, false);
  }

  public void setRegnod(OutDataRegn value) {
    temcoreJNI.OutRetrive_regnod_set(swigCPtr, this, OutDataRegn.getCPtr(value), value);
  }

  public OutDataRegn getRegnod() {
    long cPtr = temcoreJNI.OutRetrive_regnod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OutDataRegn(cPtr, false);
  }

  public void setResod(RestartData value) {
    temcoreJNI.OutRetrive_resod_set(swigCPtr, this, RestartData.getCPtr(value), value);
  }

  public RestartData getResod() {
    long cPtr = temcoreJNI.OutRetrive_resod_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RestartData(cPtr, false);
  }

  public void setDimensionData(CohortData cdp) {
    temcoreJNI.OutRetrive_setDimensionData(swigCPtr, this, CohortData.getCPtr(cdp), cdp);
  }

  public void setProcessData(int ip, EnvData edp, BgcData bdp) {
    temcoreJNI.OutRetrive_setProcessData(swigCPtr, this, ip, EnvData.getCPtr(edp), edp, BgcData.getCPtr(bdp), bdp);
  }

  public void setFireData(FirData fdp) {
    temcoreJNI.OutRetrive_setFireData(swigCPtr, this, FirData.getCPtr(fdp), fdp);
  }

  public void setRegnOutData(OutDataRegn regnodp) {
    temcoreJNI.OutRetrive_setRegnOutData(swigCPtr, this, OutDataRegn.getCPtr(regnodp), regnodp);
  }

  public void setRestartOutData(RestartData resodp) {
    temcoreJNI.OutRetrive_setRestartOutData(swigCPtr, this, RestartData.getCPtr(resodp), resodp);
  }

  public void assignSiteDlyOutputBuffer_Env(snwstate_dim d_snow, int ipft, int iday) {
    temcoreJNI.OutRetrive_assignSiteDlyOutputBuffer_Env(swigCPtr, this, snwstate_dim.getCPtr(d_snow), d_snow, ipft, iday);
  }

  public void assignSiteDlyOutputBuffer_Bgc(int ipft, int iday) {
    temcoreJNI.OutRetrive_assignSiteDlyOutputBuffer_Bgc(swigCPtr, this, ipft, iday);
  }

  public void updateRegnOutputBuffer(int im) {
    temcoreJNI.OutRetrive_updateRegnOutputBuffer(swigCPtr, this, im);
  }

  public void updateRestartOutputBuffer() {
    temcoreJNI.OutRetrive_updateRestartOutputBuffer(swigCPtr, this);
  }

}
