/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public final class outvarlistkey {
  public final static outvarlistkey I_growstart = new outvarlistkey("I_growstart", temcoreJNI.I_growstart_get());
  public final static outvarlistkey I_growend = new outvarlistkey("I_growend");
  public final static outvarlistkey I_vegcov = new outvarlistkey("I_vegcov");
  public final static outvarlistkey I_vegage = new outvarlistkey("I_vegage");
  public final static outvarlistkey I_lai = new outvarlistkey("I_lai");
  public final static outvarlistkey I_vegc = new outvarlistkey("I_vegc");
  public final static outvarlistkey I_leafc = new outvarlistkey("I_leafc");
  public final static outvarlistkey I_stemc = new outvarlistkey("I_stemc");
  public final static outvarlistkey I_rootc = new outvarlistkey("I_rootc");
  public final static outvarlistkey I_vegn = new outvarlistkey("I_vegn");
  public final static outvarlistkey I_labn = new outvarlistkey("I_labn");
  public final static outvarlistkey I_leafn = new outvarlistkey("I_leafn");
  public final static outvarlistkey I_stemn = new outvarlistkey("I_stemn");
  public final static outvarlistkey I_rootn = new outvarlistkey("I_rootn");
  public final static outvarlistkey I_gpp = new outvarlistkey("I_gpp");
  public final static outvarlistkey I_npp = new outvarlistkey("I_npp");
  public final static outvarlistkey I_ltrfalc = new outvarlistkey("I_ltrfalc");
  public final static outvarlistkey I_ltrfaln = new outvarlistkey("I_ltrfaln");
  public final static outvarlistkey I_nuptake = new outvarlistkey("I_nuptake");
  public final static outvarlistkey I_permafrost = new outvarlistkey("I_permafrost");
  public final static outvarlistkey I_mossdz = new outvarlistkey("I_mossdz");
  public final static outvarlistkey I_oshlwdz = new outvarlistkey("I_oshlwdz");
  public final static outvarlistkey I_odeepdz = new outvarlistkey("I_odeepdz");
  public final static outvarlistkey I_mineadz = new outvarlistkey("I_mineadz");
  public final static outvarlistkey I_minebdz = new outvarlistkey("I_minebdz");
  public final static outvarlistkey I_minecdz = new outvarlistkey("I_minecdz");
  public final static outvarlistkey I_oshlwc = new outvarlistkey("I_oshlwc");
  public final static outvarlistkey I_odeepc = new outvarlistkey("I_odeepc");
  public final static outvarlistkey I_mineac = new outvarlistkey("I_mineac");
  public final static outvarlistkey I_minebc = new outvarlistkey("I_minebc");
  public final static outvarlistkey I_minecc = new outvarlistkey("I_minecc");
  public final static outvarlistkey I_orgn = new outvarlistkey("I_orgn");
  public final static outvarlistkey I_avln = new outvarlistkey("I_avln");
  public final static outvarlistkey I_rh = new outvarlistkey("I_rh");
  public final static outvarlistkey I_netnmin = new outvarlistkey("I_netnmin");
  public final static outvarlistkey I_orgninput = new outvarlistkey("I_orgninput");
  public final static outvarlistkey I_avlninput = new outvarlistkey("I_avlninput");
  public final static outvarlistkey I_doclost = new outvarlistkey("I_doclost");
  public final static outvarlistkey I_orgnlost = new outvarlistkey("I_orgnlost");
  public final static outvarlistkey I_avlnlost = new outvarlistkey("I_avlnlost");
  public final static outvarlistkey I_eet = new outvarlistkey("I_eet");
  public final static outvarlistkey I_pet = new outvarlistkey("I_pet");
  public final static outvarlistkey I_qinfl = new outvarlistkey("I_qinfl");
  public final static outvarlistkey I_qdrain = new outvarlistkey("I_qdrain");
  public final static outvarlistkey I_qrunoff = new outvarlistkey("I_qrunoff");
  public final static outvarlistkey I_snwthick = new outvarlistkey("I_snwthick");
  public final static outvarlistkey I_swe = new outvarlistkey("I_swe");
  public final static outvarlistkey I_wtd = new outvarlistkey("I_wtd");
  public final static outvarlistkey I_alc = new outvarlistkey("I_alc");
  public final static outvarlistkey I_ald = new outvarlistkey("I_ald");
  public final static outvarlistkey I_vwcshlw = new outvarlistkey("I_vwcshlw");
  public final static outvarlistkey I_vwcdeep = new outvarlistkey("I_vwcdeep");
  public final static outvarlistkey I_vwcminea = new outvarlistkey("I_vwcminea");
  public final static outvarlistkey I_vwcmineb = new outvarlistkey("I_vwcmineb");
  public final static outvarlistkey I_vwcminec = new outvarlistkey("I_vwcminec");
  public final static outvarlistkey I_tshlw = new outvarlistkey("I_tshlw");
  public final static outvarlistkey I_tdeep = new outvarlistkey("I_tdeep");
  public final static outvarlistkey I_tminea = new outvarlistkey("I_tminea");
  public final static outvarlistkey I_tmineb = new outvarlistkey("I_tmineb");
  public final static outvarlistkey I_tminec = new outvarlistkey("I_tminec");
  public final static outvarlistkey I_tbotrock = new outvarlistkey("I_tbotrock");
  public final static outvarlistkey I_hkshlw = new outvarlistkey("I_hkshlw");
  public final static outvarlistkey I_hkdeep = new outvarlistkey("I_hkdeep");
  public final static outvarlistkey I_hkminea = new outvarlistkey("I_hkminea");
  public final static outvarlistkey I_hkmineb = new outvarlistkey("I_hkmineb");
  public final static outvarlistkey I_hkminec = new outvarlistkey("I_hkminec");
  public final static outvarlistkey I_tcshlw = new outvarlistkey("I_tcshlw");
  public final static outvarlistkey I_tcdeep = new outvarlistkey("I_tcdeep");
  public final static outvarlistkey I_tcminea = new outvarlistkey("I_tcminea");
  public final static outvarlistkey I_tcmineb = new outvarlistkey("I_tcmineb");
  public final static outvarlistkey I_tcminec = new outvarlistkey("I_tcminec");
  public final static outvarlistkey I_burnthick = new outvarlistkey("I_burnthick");
  public final static outvarlistkey I_burnsoic = new outvarlistkey("I_burnsoic");
  public final static outvarlistkey I_burnvegc = new outvarlistkey("I_burnvegc");
  public final static outvarlistkey I_burnsoin = new outvarlistkey("I_burnsoin");
  public final static outvarlistkey I_burnvegn = new outvarlistkey("I_burnvegn");
  public final static outvarlistkey I_burnretainc = new outvarlistkey("I_burnretainc");
  public final static outvarlistkey I_burnretainn = new outvarlistkey("I_burnretainn");
  public final static outvarlistkey I_outvarno = new outvarlistkey("I_outvarno");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static outvarlistkey swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + outvarlistkey.class + " with value " + swigValue);
  }

  private outvarlistkey(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private outvarlistkey(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private outvarlistkey(String swigName, outvarlistkey swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static outvarlistkey[] swigValues = { I_growstart, I_growend, I_vegcov, I_vegage, I_lai, I_vegc, I_leafc, I_stemc, I_rootc, I_vegn, I_labn, I_leafn, I_stemn, I_rootn, I_gpp, I_npp, I_ltrfalc, I_ltrfaln, I_nuptake, I_permafrost, I_mossdz, I_oshlwdz, I_odeepdz, I_mineadz, I_minebdz, I_minecdz, I_oshlwc, I_odeepc, I_mineac, I_minebc, I_minecc, I_orgn, I_avln, I_rh, I_netnmin, I_orgninput, I_avlninput, I_doclost, I_orgnlost, I_avlnlost, I_eet, I_pet, I_qinfl, I_qdrain, I_qrunoff, I_snwthick, I_swe, I_wtd, I_alc, I_ald, I_vwcshlw, I_vwcdeep, I_vwcminea, I_vwcmineb, I_vwcminec, I_tshlw, I_tdeep, I_tminea, I_tmineb, I_tminec, I_tbotrock, I_hkshlw, I_hkdeep, I_hkminea, I_hkmineb, I_hkminec, I_tcshlw, I_tcdeep, I_tcminea, I_tcmineb, I_tcminec, I_burnthick, I_burnsoic, I_burnvegc, I_burnsoin, I_burnvegn, I_burnretainc, I_burnretainn, I_outvarno };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

