/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class snwdiag_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected snwdiag_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(snwdiag_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_snwdiag_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSnowfreeFst(int value) {
    temcoreJNI.snwdiag_env_snowfreeFst_set(swigCPtr, this, value);
  }

  public int getSnowfreeFst() {
    return temcoreJNI.snwdiag_env_snowfreeFst_get(swigCPtr, this);
  }

  public void setSnowfreeLst(int value) {
    temcoreJNI.snwdiag_env_snowfreeLst_set(swigCPtr, this, value);
  }

  public int getSnowfreeLst() {
    return temcoreJNI.snwdiag_env_snowfreeLst_get(swigCPtr, this);
  }

  public void setTcond(double[] value) {
    temcoreJNI.snwdiag_env_tcond_set(swigCPtr, this, value);
  }

  public double[] getTcond() {
    return temcoreJNI.snwdiag_env_tcond_get(swigCPtr, this);
  }

  public void setFcmelt(double value) {
    temcoreJNI.snwdiag_env_fcmelt_set(swigCPtr, this, value);
  }

  public double getFcmelt() {
    return temcoreJNI.snwdiag_env_fcmelt_get(swigCPtr, this);
  }

  public snwdiag_env() {
    this(temcoreJNI.new_snwdiag_env(), true);
  }

}
