/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soi2atm_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soi2atm_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soi2atm_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soi2atm_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRhwdeb(double value) {
    temcoreJNI.soi2atm_bgc_rhwdeb_set(swigCPtr, this, value);
  }

  public double getRhwdeb() {
    return temcoreJNI.soi2atm_bgc_rhwdeb_get(swigCPtr, this);
  }

  public void setRhmossc(double value) {
    temcoreJNI.soi2atm_bgc_rhmossc_set(swigCPtr, this, value);
  }

  public double getRhmossc() {
    return temcoreJNI.soi2atm_bgc_rhmossc_get(swigCPtr, this);
  }

  public void setRhrawc(double[] value) {
    temcoreJNI.soi2atm_bgc_rhrawc_set(swigCPtr, this, value);
  }

  public double[] getRhrawc() {
    return temcoreJNI.soi2atm_bgc_rhrawc_get(swigCPtr, this);
  }

  public void setRhsoma(double[] value) {
    temcoreJNI.soi2atm_bgc_rhsoma_set(swigCPtr, this, value);
  }

  public double[] getRhsoma() {
    return temcoreJNI.soi2atm_bgc_rhsoma_get(swigCPtr, this);
  }

  public void setRhsompr(double[] value) {
    temcoreJNI.soi2atm_bgc_rhsompr_set(swigCPtr, this, value);
  }

  public double[] getRhsompr() {
    return temcoreJNI.soi2atm_bgc_rhsompr_get(swigCPtr, this);
  }

  public void setRhsomcr(double[] value) {
    temcoreJNI.soi2atm_bgc_rhsomcr_set(swigCPtr, this, value);
  }

  public double[] getRhsomcr() {
    return temcoreJNI.soi2atm_bgc_rhsomcr_get(swigCPtr, this);
  }

  public void setRhrawcsum(double value) {
    temcoreJNI.soi2atm_bgc_rhrawcsum_set(swigCPtr, this, value);
  }

  public double getRhrawcsum() {
    return temcoreJNI.soi2atm_bgc_rhrawcsum_get(swigCPtr, this);
  }

  public void setRhsomasum(double value) {
    temcoreJNI.soi2atm_bgc_rhsomasum_set(swigCPtr, this, value);
  }

  public double getRhsomasum() {
    return temcoreJNI.soi2atm_bgc_rhsomasum_get(swigCPtr, this);
  }

  public void setRhsomprsum(double value) {
    temcoreJNI.soi2atm_bgc_rhsomprsum_set(swigCPtr, this, value);
  }

  public double getRhsomprsum() {
    return temcoreJNI.soi2atm_bgc_rhsomprsum_get(swigCPtr, this);
  }

  public void setRhsomcrsum(double value) {
    temcoreJNI.soi2atm_bgc_rhsomcrsum_set(swigCPtr, this, value);
  }

  public double getRhsomcrsum() {
    return temcoreJNI.soi2atm_bgc_rhsomcrsum_get(swigCPtr, this);
  }

  public void setRhtot(double value) {
    temcoreJNI.soi2atm_bgc_rhtot_set(swigCPtr, this, value);
  }

  public double getRhtot() {
    return temcoreJNI.soi2atm_bgc_rhtot_get(swigCPtr, this);
  }

  public soi2atm_bgc() {
    this(temcoreJNI.new_soi2atm_bgc(), true);
  }

}
