/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soidiag_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soidiag_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soidiag_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soidiag_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPermafrost(int value) {
    temcoreJNI.soidiag_env_permafrost_set(swigCPtr, this, value);
  }

  public int getPermafrost() {
    return temcoreJNI.soidiag_env_permafrost_get(swigCPtr, this);
  }

  public void setUnfrzcolumn(double value) {
    temcoreJNI.soidiag_env_unfrzcolumn_set(swigCPtr, this, value);
  }

  public double getUnfrzcolumn() {
    return temcoreJNI.soidiag_env_unfrzcolumn_get(swigCPtr, this);
  }

  public void setAlc(double value) {
    temcoreJNI.soidiag_env_alc_set(swigCPtr, this, value);
  }

  public double getAlc() {
    return temcoreJNI.soidiag_env_alc_get(swigCPtr, this);
  }

  public void setAld(double value) {
    temcoreJNI.soidiag_env_ald_set(swigCPtr, this, value);
  }

  public double getAld() {
    return temcoreJNI.soidiag_env_ald_get(swigCPtr, this);
  }

  public void setRtdpts(double value) {
    temcoreJNI.soidiag_env_rtdpts_set(swigCPtr, this, value);
  }

  public double getRtdpts() {
    return temcoreJNI.soidiag_env_rtdpts_get(swigCPtr, this);
  }

  public void setRtdpthawpct(double value) {
    temcoreJNI.soidiag_env_rtdpthawpct_set(swigCPtr, this, value);
  }

  public double getRtdpthawpct() {
    return temcoreJNI.soidiag_env_rtdpthawpct_get(swigCPtr, this);
  }

  public void setRtdpgdd(double value) {
    temcoreJNI.soidiag_env_rtdpgdd_set(swigCPtr, this, value);
  }

  public double getRtdpgdd() {
    return temcoreJNI.soidiag_env_rtdpgdd_get(swigCPtr, this);
  }

  public void setRtdpgrowstart(int value) {
    temcoreJNI.soidiag_env_rtdpgrowstart_set(swigCPtr, this, value);
  }

  public int getRtdpgrowstart() {
    return temcoreJNI.soidiag_env_rtdpgrowstart_get(swigCPtr, this);
  }

  public void setRtdpgrowend(int value) {
    temcoreJNI.soidiag_env_rtdpgrowend_set(swigCPtr, this, value);
  }

  public int getRtdpgrowend() {
    return temcoreJNI.soidiag_env_rtdpgrowend_get(swigCPtr, this);
  }

  public void setNfactor(double value) {
    temcoreJNI.soidiag_env_nfactor_set(swigCPtr, this, value);
  }

  public double getNfactor() {
    return temcoreJNI.soidiag_env_nfactor_get(swigCPtr, this);
  }

  public void setVwc(double[] value) {
    temcoreJNI.soidiag_env_vwc_set(swigCPtr, this, value);
  }

  public double[] getVwc() {
    return temcoreJNI.soidiag_env_vwc_get(swigCPtr, this);
  }

  public void setIwc(double[] value) {
    temcoreJNI.soidiag_env_iwc_set(swigCPtr, this, value);
  }

  public double[] getIwc() {
    return temcoreJNI.soidiag_env_iwc_get(swigCPtr, this);
  }

  public void setLwc(double[] value) {
    temcoreJNI.soidiag_env_lwc_set(swigCPtr, this, value);
  }

  public double[] getLwc() {
    return temcoreJNI.soidiag_env_lwc_get(swigCPtr, this);
  }

  public void setSws(double[] value) {
    temcoreJNI.soidiag_env_sws_set(swigCPtr, this, value);
  }

  public double[] getSws() {
    return temcoreJNI.soidiag_env_sws_get(swigCPtr, this);
  }

  public void setAws(double[] value) {
    temcoreJNI.soidiag_env_aws_set(swigCPtr, this, value);
  }

  public double[] getAws() {
    return temcoreJNI.soidiag_env_aws_get(swigCPtr, this);
  }

  public void setMinliq(double[] value) {
    temcoreJNI.soidiag_env_minliq_set(swigCPtr, this, value);
  }

  public double[] getMinliq() {
    return temcoreJNI.soidiag_env_minliq_get(swigCPtr, this);
  }

  public void setTcond(double[] value) {
    temcoreJNI.soidiag_env_tcond_set(swigCPtr, this, value);
  }

  public double[] getTcond() {
    return temcoreJNI.soidiag_env_tcond_get(swigCPtr, this);
  }

  public void setHcond(double[] value) {
    temcoreJNI.soidiag_env_hcond_set(swigCPtr, this, value);
  }

  public double[] getHcond() {
    return temcoreJNI.soidiag_env_hcond_get(swigCPtr, this);
  }

  public void setFbtran(double[] value) {
    temcoreJNI.soidiag_env_fbtran_set(swigCPtr, this, value);
  }

  public double[] getFbtran() {
    return temcoreJNI.soidiag_env_fbtran_get(swigCPtr, this);
  }

  public void setTsave(double value) {
    temcoreJNI.soidiag_env_tsave_set(swigCPtr, this, value);
  }

  public double getTsave() {
    return temcoreJNI.soidiag_env_tsave_get(swigCPtr, this);
  }

  public void setTshlw(double value) {
    temcoreJNI.soidiag_env_tshlw_set(swigCPtr, this, value);
  }

  public double getTshlw() {
    return temcoreJNI.soidiag_env_tshlw_get(swigCPtr, this);
  }

  public void setTdeep(double value) {
    temcoreJNI.soidiag_env_tdeep_set(swigCPtr, this, value);
  }

  public double getTdeep() {
    return temcoreJNI.soidiag_env_tdeep_get(swigCPtr, this);
  }

  public void setTminea(double value) {
    temcoreJNI.soidiag_env_tminea_set(swigCPtr, this, value);
  }

  public double getTminea() {
    return temcoreJNI.soidiag_env_tminea_get(swigCPtr, this);
  }

  public void setTmineb(double value) {
    temcoreJNI.soidiag_env_tmineb_set(swigCPtr, this, value);
  }

  public double getTmineb() {
    return temcoreJNI.soidiag_env_tmineb_get(swigCPtr, this);
  }

  public void setTminec(double value) {
    temcoreJNI.soidiag_env_tminec_set(swigCPtr, this, value);
  }

  public double getTminec() {
    return temcoreJNI.soidiag_env_tminec_get(swigCPtr, this);
  }

  public void setTbotrock(double value) {
    temcoreJNI.soidiag_env_tbotrock_set(swigCPtr, this, value);
  }

  public double getTbotrock() {
    return temcoreJNI.soidiag_env_tbotrock_get(swigCPtr, this);
  }

  public void setTcshlw(double value) {
    temcoreJNI.soidiag_env_tcshlw_set(swigCPtr, this, value);
  }

  public double getTcshlw() {
    return temcoreJNI.soidiag_env_tcshlw_get(swigCPtr, this);
  }

  public void setTcdeep(double value) {
    temcoreJNI.soidiag_env_tcdeep_set(swigCPtr, this, value);
  }

  public double getTcdeep() {
    return temcoreJNI.soidiag_env_tcdeep_get(swigCPtr, this);
  }

  public void setTcminea(double value) {
    temcoreJNI.soidiag_env_tcminea_set(swigCPtr, this, value);
  }

  public double getTcminea() {
    return temcoreJNI.soidiag_env_tcminea_get(swigCPtr, this);
  }

  public void setTcmineb(double value) {
    temcoreJNI.soidiag_env_tcmineb_set(swigCPtr, this, value);
  }

  public double getTcmineb() {
    return temcoreJNI.soidiag_env_tcmineb_get(swigCPtr, this);
  }

  public void setTcminec(double value) {
    temcoreJNI.soidiag_env_tcminec_set(swigCPtr, this, value);
  }

  public double getTcminec() {
    return temcoreJNI.soidiag_env_tcminec_get(swigCPtr, this);
  }

  public void setFrasat(double value) {
    temcoreJNI.soidiag_env_frasat_set(swigCPtr, this, value);
  }

  public double getFrasat() {
    return temcoreJNI.soidiag_env_frasat_get(swigCPtr, this);
  }

  public void setLiqsum(double value) {
    temcoreJNI.soidiag_env_liqsum_set(swigCPtr, this, value);
  }

  public double getLiqsum() {
    return temcoreJNI.soidiag_env_liqsum_get(swigCPtr, this);
  }

  public void setIcesum(double value) {
    temcoreJNI.soidiag_env_icesum_set(swigCPtr, this, value);
  }

  public double getIcesum() {
    return temcoreJNI.soidiag_env_icesum_get(swigCPtr, this);
  }

  public void setVwcshlw(double value) {
    temcoreJNI.soidiag_env_vwcshlw_set(swigCPtr, this, value);
  }

  public double getVwcshlw() {
    return temcoreJNI.soidiag_env_vwcshlw_get(swigCPtr, this);
  }

  public void setVwcdeep(double value) {
    temcoreJNI.soidiag_env_vwcdeep_set(swigCPtr, this, value);
  }

  public double getVwcdeep() {
    return temcoreJNI.soidiag_env_vwcdeep_get(swigCPtr, this);
  }

  public void setVwcminea(double value) {
    temcoreJNI.soidiag_env_vwcminea_set(swigCPtr, this, value);
  }

  public double getVwcminea() {
    return temcoreJNI.soidiag_env_vwcminea_get(swigCPtr, this);
  }

  public void setVwcmineb(double value) {
    temcoreJNI.soidiag_env_vwcmineb_set(swigCPtr, this, value);
  }

  public double getVwcmineb() {
    return temcoreJNI.soidiag_env_vwcmineb_get(swigCPtr, this);
  }

  public void setVwcminec(double value) {
    temcoreJNI.soidiag_env_vwcminec_set(swigCPtr, this, value);
  }

  public double getVwcminec() {
    return temcoreJNI.soidiag_env_vwcminec_get(swigCPtr, this);
  }

  public void setHkshlw(double value) {
    temcoreJNI.soidiag_env_hkshlw_set(swigCPtr, this, value);
  }

  public double getHkshlw() {
    return temcoreJNI.soidiag_env_hkshlw_get(swigCPtr, this);
  }

  public void setHkdeep(double value) {
    temcoreJNI.soidiag_env_hkdeep_set(swigCPtr, this, value);
  }

  public double getHkdeep() {
    return temcoreJNI.soidiag_env_hkdeep_get(swigCPtr, this);
  }

  public void setHkminea(double value) {
    temcoreJNI.soidiag_env_hkminea_set(swigCPtr, this, value);
  }

  public double getHkminea() {
    return temcoreJNI.soidiag_env_hkminea_get(swigCPtr, this);
  }

  public void setHkmineb(double value) {
    temcoreJNI.soidiag_env_hkmineb_set(swigCPtr, this, value);
  }

  public double getHkmineb() {
    return temcoreJNI.soidiag_env_hkmineb_get(swigCPtr, this);
  }

  public void setHkminec(double value) {
    temcoreJNI.soidiag_env_hkminec_set(swigCPtr, this, value);
  }

  public double getHkminec() {
    return temcoreJNI.soidiag_env_hkminec_get(swigCPtr, this);
  }

  public soidiag_env() {
    this(temcoreJNI.new_soidiag_env(), true);
  }

}
