/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soidiag_bgc {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soidiag_bgc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soidiag_bgc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soidiag_bgc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKnmoist(double[] value) {
    temcoreJNI.soidiag_bgc_knmoist_set(swigCPtr, this, value);
  }

  public double[] getKnmoist() {
    return temcoreJNI.soidiag_bgc_knmoist_get(swigCPtr, this);
  }

  public void setRhmoist(double[] value) {
    temcoreJNI.soidiag_bgc_rhmoist_set(swigCPtr, this, value);
  }

  public double[] getRhmoist() {
    return temcoreJNI.soidiag_bgc_rhmoist_get(swigCPtr, this);
  }

  public void setRhq10(double[] value) {
    temcoreJNI.soidiag_bgc_rhq10_set(swigCPtr, this, value);
  }

  public double[] getRhq10() {
    return temcoreJNI.soidiag_bgc_rhq10_get(swigCPtr, this);
  }

  public void setLtrfcn(double[] value) {
    temcoreJNI.soidiag_bgc_ltrfcn_set(swigCPtr, this, value);
  }

  public double[] getLtrfcn() {
    return temcoreJNI.soidiag_bgc_ltrfcn_get(swigCPtr, this);
  }

  public void setTsomc(double[] value) {
    temcoreJNI.soidiag_bgc_tsomc_set(swigCPtr, this, value);
  }

  public double[] getTsomc() {
    return temcoreJNI.soidiag_bgc_tsomc_get(swigCPtr, this);
  }

  public void setShlwc(double value) {
    temcoreJNI.soidiag_bgc_shlwc_set(swigCPtr, this, value);
  }

  public double getShlwc() {
    return temcoreJNI.soidiag_bgc_shlwc_get(swigCPtr, this);
  }

  public void setDeepc(double value) {
    temcoreJNI.soidiag_bgc_deepc_set(swigCPtr, this, value);
  }

  public double getDeepc() {
    return temcoreJNI.soidiag_bgc_deepc_get(swigCPtr, this);
  }

  public void setMineac(double value) {
    temcoreJNI.soidiag_bgc_mineac_set(swigCPtr, this, value);
  }

  public double getMineac() {
    return temcoreJNI.soidiag_bgc_mineac_get(swigCPtr, this);
  }

  public void setMinebc(double value) {
    temcoreJNI.soidiag_bgc_minebc_set(swigCPtr, this, value);
  }

  public double getMinebc() {
    return temcoreJNI.soidiag_bgc_minebc_get(swigCPtr, this);
  }

  public void setMinecc(double value) {
    temcoreJNI.soidiag_bgc_minecc_set(swigCPtr, this, value);
  }

  public double getMinecc() {
    return temcoreJNI.soidiag_bgc_minecc_get(swigCPtr, this);
  }

  public void setRawcsum(double value) {
    temcoreJNI.soidiag_bgc_rawcsum_set(swigCPtr, this, value);
  }

  public double getRawcsum() {
    return temcoreJNI.soidiag_bgc_rawcsum_get(swigCPtr, this);
  }

  public void setSomasum(double value) {
    temcoreJNI.soidiag_bgc_somasum_set(swigCPtr, this, value);
  }

  public double getSomasum() {
    return temcoreJNI.soidiag_bgc_somasum_get(swigCPtr, this);
  }

  public void setSomprsum(double value) {
    temcoreJNI.soidiag_bgc_somprsum_set(swigCPtr, this, value);
  }

  public double getSomprsum() {
    return temcoreJNI.soidiag_bgc_somprsum_get(swigCPtr, this);
  }

  public void setSomcrsum(double value) {
    temcoreJNI.soidiag_bgc_somcrsum_set(swigCPtr, this, value);
  }

  public double getSomcrsum() {
    return temcoreJNI.soidiag_bgc_somcrsum_get(swigCPtr, this);
  }

  public void setOrgnsum(double value) {
    temcoreJNI.soidiag_bgc_orgnsum_set(swigCPtr, this, value);
  }

  public double getOrgnsum() {
    return temcoreJNI.soidiag_bgc_orgnsum_get(swigCPtr, this);
  }

  public void setAvlnsum(double value) {
    temcoreJNI.soidiag_bgc_avlnsum_set(swigCPtr, this, value);
  }

  public double getAvlnsum() {
    return temcoreJNI.soidiag_bgc_avlnsum_get(swigCPtr, this);
  }

  public soidiag_bgc() {
    this(temcoreJNI.new_soidiag_bgc(), true);
  }

}
