/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soipar_dim {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soipar_dim(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soipar_dim obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soipar_dim(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxmossthick(double value) {
    temcoreJNI.soipar_dim_maxmossthick_set(swigCPtr, this, value);
  }

  public double getMaxmossthick() {
    return temcoreJNI.soipar_dim_maxmossthick_get(swigCPtr, this);
  }

  public void setMinmossthick(double value) {
    temcoreJNI.soipar_dim_minmossthick_set(swigCPtr, this, value);
  }

  public double getMinmossthick() {
    return temcoreJNI.soipar_dim_minmossthick_get(swigCPtr, this);
  }

  public void setCoefmossa(double value) {
    temcoreJNI.soipar_dim_coefmossa_set(swigCPtr, this, value);
  }

  public double getCoefmossa() {
    return temcoreJNI.soipar_dim_coefmossa_get(swigCPtr, this);
  }

  public void setCoefmossb(double value) {
    temcoreJNI.soipar_dim_coefmossb_set(swigCPtr, this, value);
  }

  public double getCoefmossb() {
    return temcoreJNI.soipar_dim_coefmossb_get(swigCPtr, this);
  }

  public void setMinshlwthick(double value) {
    temcoreJNI.soipar_dim_minshlwthick_set(swigCPtr, this, value);
  }

  public double getMinshlwthick() {
    return temcoreJNI.soipar_dim_minshlwthick_get(swigCPtr, this);
  }

  public void setCoefshlwa(double value) {
    temcoreJNI.soipar_dim_coefshlwa_set(swigCPtr, this, value);
  }

  public double getCoefshlwa() {
    return temcoreJNI.soipar_dim_coefshlwa_get(swigCPtr, this);
  }

  public void setCoefshlwb(double value) {
    temcoreJNI.soipar_dim_coefshlwb_set(swigCPtr, this, value);
  }

  public double getCoefshlwb() {
    return temcoreJNI.soipar_dim_coefshlwb_get(swigCPtr, this);
  }

  public void setMindeepthick(double value) {
    temcoreJNI.soipar_dim_mindeepthick_set(swigCPtr, this, value);
  }

  public double getMindeepthick() {
    return temcoreJNI.soipar_dim_mindeepthick_get(swigCPtr, this);
  }

  public void setCoefdeepa(double value) {
    temcoreJNI.soipar_dim_coefdeepa_set(swigCPtr, this, value);
  }

  public double getCoefdeepa() {
    return temcoreJNI.soipar_dim_coefdeepa_get(swigCPtr, this);
  }

  public void setCoefdeepb(double value) {
    temcoreJNI.soipar_dim_coefdeepb_set(swigCPtr, this, value);
  }

  public double getCoefdeepb() {
    return temcoreJNI.soipar_dim_coefdeepb_get(swigCPtr, this);
  }

  public void setCoefminea(double value) {
    temcoreJNI.soipar_dim_coefminea_set(swigCPtr, this, value);
  }

  public double getCoefminea() {
    return temcoreJNI.soipar_dim_coefminea_get(swigCPtr, this);
  }

  public void setCoefmineb(double value) {
    temcoreJNI.soipar_dim_coefmineb_set(swigCPtr, this, value);
  }

  public double getCoefmineb() {
    return temcoreJNI.soipar_dim_coefmineb_get(swigCPtr, this);
  }

  public soipar_dim() {
    this(temcoreJNI.new_soipar_dim(), true);
  }

}
