/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class soistate_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected soistate_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(soistate_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_soistate_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrozen(double[] value) {
    temcoreJNI.soistate_env_frozen_set(swigCPtr, this, value);
  }

  public double[] getFrozen() {
    return temcoreJNI.soistate_env_frozen_get(swigCPtr, this);
  }

  public void setFrozenfrac(double[] value) {
    temcoreJNI.soistate_env_frozenfrac_set(swigCPtr, this, value);
  }

  public double[] getFrozenfrac() {
    return temcoreJNI.soistate_env_frozenfrac_get(swigCPtr, this);
  }

  public void setTs(double[] value) {
    temcoreJNI.soistate_env_ts_set(swigCPtr, this, value);
  }

  public double[] getTs() {
    return temcoreJNI.soistate_env_ts_get(swigCPtr, this);
  }

  public void setLiq(double[] value) {
    temcoreJNI.soistate_env_liq_set(swigCPtr, this, value);
  }

  public double[] getLiq() {
    return temcoreJNI.soistate_env_liq_get(swigCPtr, this);
  }

  public void setIce(double[] value) {
    temcoreJNI.soistate_env_ice_set(swigCPtr, this, value);
  }

  public double[] getIce() {
    return temcoreJNI.soistate_env_ice_get(swigCPtr, this);
  }

  public void setTrock(double[] value) {
    temcoreJNI.soistate_env_trock_set(swigCPtr, this, value);
  }

  public double[] getTrock() {
    return temcoreJNI.soistate_env_trock_get(swigCPtr, this);
  }

  public void setFrontstype(int[] value) {
    temcoreJNI.soistate_env_frontstype_set(swigCPtr, this, value);
  }

  public int[] getFrontstype() {
    return temcoreJNI.soistate_env_frontstype_get(swigCPtr, this);
  }

  public void setFrontsz(double[] value) {
    temcoreJNI.soistate_env_frontsz_set(swigCPtr, this, value);
  }

  public double[] getFrontsz() {
    return temcoreJNI.soistate_env_frontsz_get(swigCPtr, this);
  }

  public void setWatertab(double value) {
    temcoreJNI.soistate_env_watertab_set(swigCPtr, this, value);
  }

  public double getWatertab() {
    return temcoreJNI.soistate_env_watertab_get(swigCPtr, this);
  }

  public void setDraindepth(double value) {
    temcoreJNI.soistate_env_draindepth_set(swigCPtr, this, value);
  }

  public double getDraindepth() {
    return temcoreJNI.soistate_env_draindepth_get(swigCPtr, this);
  }

  public soistate_env() {
    this(temcoreJNI.new_soistate_env(), true);
  }

}
