/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class SWIGTYPE_p_a_31__oneenv {
  private long swigCPtr;

  protected SWIGTYPE_p_a_31__oneenv(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_a_31__oneenv() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_a_31__oneenv obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

