/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class temcore {
  public static int getNUM_CMT() {
    return temcoreJNI.NUM_CMT_get();
  }

  public static int getNUM_PFT() {
    return temcoreJNI.NUM_PFT_get();
  }

  public static int getNUM_PFT_PART() {
    return temcoreJNI.NUM_PFT_PART_get();
  }

  public static int getMAX_DRG_TYPE() {
    return temcoreJNI.MAX_DRG_TYPE_get();
  }

  public static int getNUM_FSEVR() {
    return temcoreJNI.NUM_FSEVR_get();
  }

  public static int getNUM_FSEASON() {
    return temcoreJNI.NUM_FSEASON_get();
  }

  public static int getNUM_FSIZE() {
    return temcoreJNI.NUM_FSIZE_get();
  }

  public static int getMAX_SNW_LAY() {
    return temcoreJNI.MAX_SNW_LAY_get();
  }

  public static int getMAX_MOS_LAY() {
    return temcoreJNI.MAX_MOS_LAY_get();
  }

  public static int getMAX_SLW_LAY() {
    return temcoreJNI.MAX_SLW_LAY_get();
  }

  public static int getMAX_DEP_LAY() {
    return temcoreJNI.MAX_DEP_LAY_get();
  }

  public static int getMAX_MIN_LAY() {
    return temcoreJNI.MAX_MIN_LAY_get();
  }

  public static double[] getMINETHICK() {
    return temcoreJNI.MINETHICK_get();
  }

  public static int[] getMINEZONE() {
    return temcoreJNI.MINEZONE_get();
  }

  public static int getMAX_ROC_LAY() {
    return temcoreJNI.MAX_ROC_LAY_get();
  }

  public static double[] getROCKTHICK() {
    return temcoreJNI.ROCKTHICK_get();
  }

  public static int getMAX_SOI_LAY() {
    return temcoreJNI.MAX_SOI_LAY_get();
  }

  public static int getMAX_GRN_LAY() {
    return temcoreJNI.MAX_GRN_LAY_get();
  }

  public static int getMAX_NUM_FNT() {
    return temcoreJNI.MAX_NUM_FNT_get();
  }

  public static int getMAX_ROT_LAY() {
    return temcoreJNI.MAX_ROT_LAY_get();
  }

  public static double[] getROOTTHICK() {
    return temcoreJNI.ROOTTHICK_get();
  }

  public static double getMINSLWTHICK() {
    return temcoreJNI.MINSLWTHICK_get();
  }

  public static double getMINDEPTHICK() {
    return temcoreJNI.MINDEPTHICK_get();
  }

  public static int getNUM_VEG_STATE() {
    return temcoreJNI.NUM_VEG_STATE_get();
  }

  public static int getNUM_SOI_STATE() {
    return temcoreJNI.NUM_SOI_STATE_get();
  }

  public static int getMAXSTATE() {
    return temcoreJNI.MAXSTATE_get();
  }

  public static int getNUM_VEG_FLUX() {
    return temcoreJNI.NUM_VEG_FLUX_get();
  }

  public static int getNUM_SOI_FLUX() {
    return temcoreJNI.NUM_SOI_FLUX_get();
  }

  public static int getNUMEQ_VEG() {
    return temcoreJNI.NUMEQ_VEG_get();
  }

  public static int getNUMEQ_SOI() {
    return temcoreJNI.NUMEQ_SOI_get();
  }

  public static int getNUMEQ() {
    return temcoreJNI.NUMEQ_get();
  }

  public static int getMONTHLY() {
    return temcoreJNI.MONTHLY_get();
  }

  public static int getDAILY() {
    return temcoreJNI.DAILY_get();
  }

  public static int getDINY() {
    return temcoreJNI.DINY_get();
  }

  public static int getMINY() {
    return temcoreJNI.MINY_get();
  }

  public static int[] getDINM() {
    return temcoreJNI.DINM_get();
  }

  public static int[] getDOYINDFST() {
    return temcoreJNI.DOYINDFST_get();
  }

  public static int getMAX_FSIZE_DRV_YR() {
    return temcoreJNI.MAX_FSIZE_DRV_YR_get();
  }

  public static int getMAX_CO2_DRV_YR() {
    return temcoreJNI.MAX_CO2_DRV_YR_get();
  }

  public static int getMAX_ATM_DRV_YR() {
    return temcoreJNI.MAX_ATM_DRV_YR_get();
  }

  public static int getMAX_ATM_NOM_YR() {
    return temcoreJNI.MAX_ATM_NOM_YR_get();
  }

  public static int getMAX_VEG_SET() {
    return temcoreJNI.MAX_VEG_SET_get();
  }

  public static int getMIN_EQ_YR() {
    return temcoreJNI.MIN_EQ_YR_get();
  }

  public static int getMAX_EQ_YR() {
    return temcoreJNI.MAX_EQ_YR_get();
  }

  public static int getMAX_SP_YR() {
    return temcoreJNI.MAX_SP_YR_get();
  }

  public static int getBEG_TR_YR() {
    return temcoreJNI.BEG_TR_YR_get();
  }

  public static int getEND_TR_YR() {
    return temcoreJNI.END_TR_YR_get();
  }

  public static int getBEG_SC_YR() {
    return temcoreJNI.BEG_SC_YR_get();
  }

  public static int getEND_SC_YR() {
    return temcoreJNI.END_SC_YR_get();
  }

  public static int getEND_SP_YR() {
    return temcoreJNI.END_SP_YR_get();
  }

  public static int getBEG_SP_YR() {
    return temcoreJNI.BEG_SP_YR_get();
  }

  public static int getMAX_TR_YR() {
    return temcoreJNI.MAX_TR_YR_get();
  }

  public static int getMAX_SC_YR() {
    return temcoreJNI.MAX_SC_YR_get();
  }

  public static int getMAX_FIR_OCRNUM() {
    return temcoreJNI.MAX_FIR_OCRNUM_get();
  }

  public static int getMISSING_I() {
    return temcoreJNI.MISSING_I_get();
  }

  public static float getMISSING_F() {
    return temcoreJNI.MISSING_F_get();
  }

  public static double getMISSING_D() {
    return temcoreJNI.MISSING_D_get();
  }

  public static int getMAX_SOIL_TXTR() {
    return temcoreJNI.MAX_SOIL_TXTR_get();
  }

  public static int getMAX_SM() {
    return temcoreJNI.MAX_SM_get();
  }

  public static int getMAX_ST1() {
    return temcoreJNI.MAX_ST1_get();
  }

  public static int getMAX_ST2() {
    return temcoreJNI.MAX_ST2_get();
  }

}
