/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public final class VASCULARKEY {
  public final static VASCULARKEY I_vascular = new VASCULARKEY("I_vascular", temcoreJNI.I_vascular_get());
  public final static VASCULARKEY I_sphagnum = new VASCULARKEY("I_sphagnum");
  public final static VASCULARKEY I_feathermoss = new VASCULARKEY("I_feathermoss");
  public final static VASCULARKEY I_other = new VASCULARKEY("I_other");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VASCULARKEY swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VASCULARKEY.class + " with value " + swigValue);
  }

  private VASCULARKEY(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VASCULARKEY(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VASCULARKEY(String swigName, VASCULARKEY swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VASCULARKEY[] swigValues = { I_vascular, I_sphagnum, I_feathermoss, I_other };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

