/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class vegpar_env {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vegpar_env(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vegpar_env obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_vegpar_env(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlbvisnir(double value) {
    temcoreJNI.vegpar_env_albvisnir_set(swigCPtr, this, value);
  }

  public double getAlbvisnir() {
    return temcoreJNI.vegpar_env_albvisnir_get(swigCPtr, this);
  }

  public void setEr(double value) {
    temcoreJNI.vegpar_env_er_set(swigCPtr, this, value);
  }

  public double getEr() {
    return temcoreJNI.vegpar_env_er_get(swigCPtr, this);
  }

  public void setIrcoef(double value) {
    temcoreJNI.vegpar_env_ircoef_set(swigCPtr, this, value);
  }

  public double getIrcoef() {
    return temcoreJNI.vegpar_env_ircoef_get(swigCPtr, this);
  }

  public void setIscoef(double value) {
    temcoreJNI.vegpar_env_iscoef_set(swigCPtr, this, value);
  }

  public double getIscoef() {
    return temcoreJNI.vegpar_env_iscoef_get(swigCPtr, this);
  }

  public void setGlmax(double value) {
    temcoreJNI.vegpar_env_glmax_set(swigCPtr, this, value);
  }

  public double getGlmax() {
    return temcoreJNI.vegpar_env_glmax_get(swigCPtr, this);
  }

  public void setGl_bl(double value) {
    temcoreJNI.vegpar_env_gl_bl_set(swigCPtr, this, value);
  }

  public double getGl_bl() {
    return temcoreJNI.vegpar_env_gl_bl_get(swigCPtr, this);
  }

  public void setGl_c(double value) {
    temcoreJNI.vegpar_env_gl_c_set(swigCPtr, this, value);
  }

  public double getGl_c() {
    return temcoreJNI.vegpar_env_gl_c_get(swigCPtr, this);
  }

  public void setVpd_open(double value) {
    temcoreJNI.vegpar_env_vpd_open_set(swigCPtr, this, value);
  }

  public double getVpd_open() {
    return temcoreJNI.vegpar_env_vpd_open_get(swigCPtr, this);
  }

  public void setVpd_close(double value) {
    temcoreJNI.vegpar_env_vpd_close_set(swigCPtr, this, value);
  }

  public double getVpd_close() {
    return temcoreJNI.vegpar_env_vpd_close_get(swigCPtr, this);
  }

  public void setPpfd50(double value) {
    temcoreJNI.vegpar_env_ppfd50_set(swigCPtr, this, value);
  }

  public double getPpfd50() {
    return temcoreJNI.vegpar_env_ppfd50_get(swigCPtr, this);
  }

  public vegpar_env() {
    this(temcoreJNI.new_vegpar_env(), true);
  }

}
