/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package TEMJNI;

public class vegpar_cal {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected vegpar_cal(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(vegpar_cal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        temcoreJNI.delete_vegpar_cal(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCmax(double value) {
    temcoreJNI.vegpar_cal_cmax_set(swigCPtr, this, value);
  }

  public double getCmax() {
    return temcoreJNI.vegpar_cal_cmax_get(swigCPtr, this);
  }

  public void setNmax(double value) {
    temcoreJNI.vegpar_cal_nmax_set(swigCPtr, this, value);
  }

  public double getNmax() {
    return temcoreJNI.vegpar_cal_nmax_get(swigCPtr, this);
  }

  public void setCfall(double[] value) {
    temcoreJNI.vegpar_cal_cfall_set(swigCPtr, this, value);
  }

  public double[] getCfall() {
    return temcoreJNI.vegpar_cal_cfall_get(swigCPtr, this);
  }

  public void setNfall(double[] value) {
    temcoreJNI.vegpar_cal_nfall_set(swigCPtr, this, value);
  }

  public double[] getNfall() {
    return temcoreJNI.vegpar_cal_nfall_get(swigCPtr, this);
  }

  public void setKra(double value) {
    temcoreJNI.vegpar_cal_kra_set(swigCPtr, this, value);
  }

  public double getKra() {
    return temcoreJNI.vegpar_cal_kra_get(swigCPtr, this);
  }

  public void setKrb(double[] value) {
    temcoreJNI.vegpar_cal_krb_set(swigCPtr, this, value);
  }

  public double[] getKrb() {
    return temcoreJNI.vegpar_cal_krb_get(swigCPtr, this);
  }

  public void setFrg(double value) {
    temcoreJNI.vegpar_cal_frg_set(swigCPtr, this, value);
  }

  public double getFrg() {
    return temcoreJNI.vegpar_cal_frg_get(swigCPtr, this);
  }

  public vegpar_cal() {
    this(temcoreJNI.new_vegpar_cal(), true);
  }

}
